---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
spec:
  postgresql:
    extensions:
      - name: pgvector
        image:
          # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.1-18-trixie

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ${APP}
spec:
  extensions:
    - name: vector
    - name: pg_trgm
    - name: uuid-ossp
