---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: truenas-exporters
spec:
  staticConfigs:
    - targets:
        - nas.mgmt.h.mirceanton.com:9100
      labels:
        job: node-exporter
        node_type: nas
    - targets:
        - nas.mgmt.h.mirceanton.com:9633
      labels:
        job: smartctl-exporter
    - targets:
        - nas.mgmt.h.mirceanton.com:8080
      labels:
        job: cadvisor
  metricsPath: /metrics
  scrapeInterval: 30s
  scrapeTimeout: 10s

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/grafana.integreatly.org/grafanadashboard_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: truenas-smartctl
spec:
  grafanaCom:
    id: 22604
    revision: 2

  datasources:
    - datasourceName: prometheus
      inputName: DS_PROMETHEUS

  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/grafana.integreatly.org/grafanadashboard_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: truenas-docker-monitoring
spec:
  datasources:
    - datasourceName: prometheus
      inputName: DS_PROMETHEUS

  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana

  resyncPeriod: 5m
  url: "https://raw.githubusercontent.com/mirceanton/home-ops/refs/heads/main/apps/monitoring-system/kube-prometheus-stack/app/scrape-configs/truenas-docker-monitoring.json"
