---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
spec:
  managed:
    roles:
      - name: ${APP}
        ensure: present
        login: true
