---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: readarr-api-key-pushsecret
spec:
  refreshInterval: 1h
  deletionPolicy: Delete
  updatePolicy: Replace

  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore

  selector:
    secret:
      name: readarr-secret

  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: Readarr API Key
          property: password
