---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bookorbit
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 15m
  targetNamespace: media

  path: ./apps/media/bookorbit/app
  components:
    - ../../../../components/cnpg/
    - ../../../../components/volsync/
    - ../../../../components/nfs-scaler/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_PUID: "568"
      VOLSYNC_PGID: "568"

  decryption: { provider: sops }
  dependsOn:
    - name: 1password-connect
      namespace: security-system
    - name: volsync
      namespace: storage-system
    - name: keda
      namespace: kube-system
    - name: cloudnative-pg-operator
      namespace: database-system
