---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ollama

  values:
    controllers:
      ollama-gpu:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ollama/ollama
              tag: 0.21.0
            env:
              TZ: Europe/Bucharest
              OLLAMA_HOST: "::"
              OLLAMA_MODELS: /models
              OLLAMA_NUM_PARALLEL: 1
              OLLAMA_CONTEXT_LENGTH: 32768
              OLLAMA_KV_CACHE_TYPE: q8_0
              OLLAMA_FLASH_ATTENTION: "true"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 11434
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              readiness: *probe
              startup: *probe

            resources:
              requests:
                cpu: 100m
                memory: 512Mi
                nvidia.com/gpu: 1
              limits:
                memory: 16Gi
                nvidia.com/gpu: 1

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      runtimeClassName: nvidia
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: ollama-gpu
        ports:
          http:
            port: *port

    persistence:
      models:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
        storageClass: openebs-zfs-cache
        globalMounts:
          - path: /models
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
