---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencode
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: opencode

  values:
    fullnameOverride: opencode

    controllers:
      opencode:
        containers:
          opencode:
            image:
              repository: ghcr.io/anomalyco/opencode
              tag: 1.14.41@sha256:e48b6ca2acdfc33026eab4c7edf24f7a32bb600a34792e2ea53684a21772713d
            command: ["opencode", "web", "--hostname", "0.0.0.0"]
            env:
              TZ: "Europe/Bucharest"
              HOME: /home/opencode

            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      opencode:
        ports:
          http:
            port: 4096

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault

    route:
      home:
        hostnames: ["code.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /home/opencode
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
