---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cnpg.yaml
  - database.yaml
  - external-secret.yaml
  - objectstore.yaml
  - scheduled-backup.yaml
  - seed.configmap.yaml
  - seed.job.yaml
