---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: home-assistant-mcp
spec:
  alias: home_assistant
  url: http://home-assistant-mcp.home-automation.svc.cluster.local:8086/mcp
  transport: http
  proxyRef: litellm
