---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./github-mcp.yaml
  - ./firefly-mcp.yaml
  - ./affine-mcp.yaml
  - ./kubesearch-mcp.yaml
  - ./flux-mcp.yaml
  - ./grafana-mcp.yaml
  - ./home-assistant-mcp.yaml
  - ./navidrome-mcp.yaml
  - ./streamarr-mcp.yaml
