---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readurr-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: readurr-secret
    creationPolicy: Owner

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: Readurr
        property: jwt_secret
