---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

spec:
  config:
    dashboards:
      min_refresh_interval: 1s

    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"

    server:
      enable_gzip: "true"
      root_url: https://grafana.admin.mirceanton.com

    auth: { disable_login_form: "true" }
    auth.anonymous: { enabled: "false" }
    metrics: { enabled: "true" }
    news: { news_feed_enabled: "false" }
    plugins: { plugin_admin_enabled: "false" }
    security: { angular_support_enabled: "true" }

    auth.generic_oauth:
      enabled: "true"
      name: Keycloak
      client_id: grafana
      client_secret: ${AUTH_CLIENT_SECRET}
      scopes: "openid profile email"
      auth_url: https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab/protocol/openid-connect/auth
      token_url: https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab/protocol/openid-connect/token
      api_url: https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab/protocol/openid-connect/userinfo
      allow_sign_up: "true"
      use_pkce: "true"

  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: AUTH_CLIENT_SECRET
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc

  httpRoute:
    spec:
      hostnames: ["grafana.admin.mirceanton.com"]
      parentRefs:
        - name: envoy-admin
          namespace: network-system
      rules:
        - backendRefs:
            - name: grafana-service
              port: 3000

  persistentVolumeClaim:
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: openebs-zfs
      resources:
        requests:
          storage: 4Gi
  disableDefaultSecurityContext: All
