---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kubesearch-mcp.yaml
  - ./truenas-mcp.yaml
  - ./github-mcp.yaml
  - ./youtube-public-mcp.yaml
  - ./channel-analytics-mcp.yaml
  - ./mikrotik-mcp.yaml
