---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name bookorbit-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: jwt_secret
      remoteRef:
        key: BookOrbit
        property: jwt_secret
    - secretKey: setup_bootstrap_token
      remoteRef:
        key: BookOrbit
        property: setup_bootstrap_token
    - secretKey: email_encryption_key
      remoteRef:
        key: BookOrbit
        property: email_encryption_key
    - secretKey: migration_encryption_key
      remoteRef:
        key: BookOrbit
        property: migration_encryption_key
