---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: papra
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: papra

  values:
    controllers:
      papra:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          papra:
            image:
              repository: ghcr.io/papra-hq/papra
              tag: 26.4.0-rootless@sha256:1de52370c82d0eb9aad101f5f06b92272cbae850f0ca3dc623fc96835f57ad68
            env:
              APP_BASE_URL: "https://documents.home.mirceanton.com"
              TZ: Europe/Bucharest
              INGESTION_FOLDER_IS_ENABLED: "true"
              INGESTION_FOLDER_POST_PROCESSING_STRATEGY: move
              AUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: papra-secret
                    key: AUTH_SECRET

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        ports:
          http:
            port: 1221

    route:
      home:
        hostnames: ["documents.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      data:
        existingClaim: ${APP}
        globalMounts:
          - path: /app/app-data
      documents:
        type: nfs
        server: nas.stor.h.mirceanton.com
        path: /mnt/tank/Media/Documents
        globalMounts:
          - path: /app/ingestion
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
