[env]
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Runtimes
node = "latest"
uv = "latest"

# Kubectl + Tools + Plugins
"aqua:kubectl" = "1.36.2"
"github:mirceanton/kubectl-switch" = "latest"
"github:josegonzalez/kubectl-eso" = "latest"
"aqua:kustomize" = "latest"
"aqua:derailed/k9s" = "latest"
"aqua:cilium/hubble" = "latest"

# Flux Tools
"aqua:fluxcd/flux2" = "2.8.8"
"github:home-operations/flate" = "latest"

# Helm + Plugins
"aqua:helm" = "latest"
helmfile = "latest"

# Talos Stuff
"aqua:talosctl" = "1.13.4"
"aqua:talhelper" = "3.1.11"
"github:mirceanton/talswitcher" = "latest"

# Misc Tools
task = "latest"
sops = "latest"
age = "latest"
direnv = "latest"
op = "latest"
yq = "latest"

# Linters
actionlint = "latest"
shellcheck = "latest"
"npm:prettier" = "latest"
