[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
# Terraform Stuff
terraform = "latest"
terragrunt = "latest"

# Talos Stuff
"aqua:siderolabs/talos" = "1.11.0"

# Encryption Tools
sops = "latest"
age = "latest"

direnv = "latest"

# =================================================================================================
# CI Tools
# =================================================================================================
gh = "latest"
actionlint = "latest"
yamllint = "latest"
"npm:@commitlint/cli" = "latest"