---
version: "3"

includes:
  cluster: .taskfiles/cluster.yaml
  lint: .taskfiles/lint.yaml
  sops: .taskfiles/sops.yaml
  volsync: .taskfiles/volsync.yaml

tasks:
  default:
    silent: true
    cmd: task -l
