---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: external-secrets

  values:
    # =============================================================================================
    # Component - Main App
    # =============================================================================================
    installCRDs: true
    leaderElect: true #! Required for more than 1 replica
    concurrent: 8
    log: { level: info }
    serviceMonitor: { enabled: true }
    grafanaDashboard: { enabled: true }

    replicaCount: 1

    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 256Mi

    podSecurityContext: { fsGroup: 1000 }
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault

    # =============================================================================================
    # Component - Cert Controller
    # =============================================================================================
    certController:
      create: true

      replicaCount: 1

      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 256Mi

      podSecurityContext: { fsGroup: 1000 }
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

    # =============================================================================================
    # Component - Webhook
    # =============================================================================================
    webhook:
      create: true

      replicaCount: 1

      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 128Mi

      podSecurityContext: { fsGroup: 1000 }
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
