---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: openebs-zfs-cache
