---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret democratic-csi-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *secret
    creationPolicy: Owner

  data:
    - secretKey: truenas-api-key
      remoteRef:
        key: Democratic CSI - TrueNAS API Credentials
        property: password
