---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/clustersecretstore_v1.json

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword.security-system.svc.cluster.local
      vaults:
        kubernetes-home-ops: 1
        mikrotik-users: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-token
            namespace: security-system
            key: token
