apiVersion: v1
kind: Secret
metadata:
    name: op-token
stringData:
    token: ENC[AES256_GCM,data:JLKMYqAzmq8psFok5r0DMwbkIwD7oiVUmriiYZwLEhK9jhkYrVTTVkimTsfhmoez7fNj9egDJdBsGGx6YJDaC/Zgql/yaB6f7UHGMx8o9vFSa8zVS7FvzSKVEl9HRWnZAYS4WUsGBQkqCGLBqPTecDHIKIo2nTakEwPIhuwx+605+3+UJhFmWlxJMMzgcuSXzea5nzOc/nRwT7vSYwAmEHWeYd7Sw4CHksV8hIQ+85lpZ9qrUFlqOJq9VsQDKEdz4r6BfwB8xQmGmwerDCeHfQXXUHUVJO9ksP4CC2eW4z+f58PP2EIBfZljrfcewRZthqoIOIn9TnEUxgD5jGM///FVEm1CxzkrOEV5joV6vmZPAy73D+FG6txcsb33LGbOwPrMIcEfe6WmpreEI4A03NXwmuj3tfIGwYbAkHGr188pdn7btDz7nAq4+Y9Q4HkC4xS5xa/nhzf4uCR1BYOsdue0ptkDgftEfgPBlnCcXL9nnAvNZ+SbrNlhjIh5mOIOB2kbbAGGWDRSKK7j/YMGa2ei481HfY1IgAGr1R0GVM15iP9dmr74fuRolt8BI5Qi3QadWVxykKMRtex5VaIGx2mGgP0W4AhvRqvOz+0h5oMY8/6xTWInFq1ReNyvnPiq96VLTk5vlI6kPGRKQN7Gc80sCSa77Hv5uofSgVGGMUzphww80vDMQIPpPmb6g9wqxhdbIIAY/VcE3Jc8V9CFIoIjbvDRStBdtOWnOXFT8i6AvK8zABYdTcggRGnRmoKjUYWqEwoUfsYMg+4COXwXpDsd+Oc6c/xgrRapzytuhVT6cYkyVn9lTbxKYJROrInc7CyLLX37JfwvPxhbMX99RWKmKrGlweFtxLDbCpn4UIveWu0Two4FhB9aNgHbYBJ4IIJ81j+VSsK6jqb151KwsGin7qhxC4C8oTi6BAZnW83P/NYaKT8/5dUwrBWPKQk6z0g0ft7ZnZ4o/jknHAMPhgwL+6T9yg7SvkyTiog7xMDna2MumUfEanVV9TCxbcH4ia0TEA8Mjxmy8XSvMuODhSOjfjSLqJc9sRdlwrEDAqpew2mfI9XNwr0jI+tv,iv:EixHUfMU5yswK03apRdiRwsGRHWzty2bqTzRTudTXzU=,tag:G+xRg9gyBeSN2R6Bh8Bm2Q==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK2xFV2FxaS92eE56M0lI
            VW1Ra1Q3VFFtdVVHWDdSMStreGk3UU9STEhrCnk2OE05UlRnRm5tSEJkaC9RY09R
            cnVHQWpyWGdEeTVSeHhKd050LzQzR1UKLS0tIGxpOVk3N2c1U0JkdEk5Q0dLc3ZP
            VEpZQnllZTUrR1ZzeC93eTU1OEcyVXMKOcX2P6VmqlSMTXa1PVPihsGPEZ51Tr5a
            lCkmh+O2VSFBX2aOsM31C12hlgvHvcc+lx3oSALUpTxHyKK92lsw5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T11:08:35Z"
    mac: ENC[AES256_GCM,data:cJxNaOmqI0dYKCz4U8nQb3tCU5EE/jOiZG0diiijZiZTuxYFH5For/wPgsliZtQibtwrc0NnxLiAJtAFuLMPHbpqlz0+qVNKzH/W7XFww7FiryV+D6UCxNSMv1UkqG16UZzPsM57SR3gRhupgj5W3L5Xl5XMfidkn65MYcri4zE=,iv:cacfbxHjGygO1Im5+FyPKVmg9B7hWZVZ0+x4KZARX+k=,tag:yEiQC1UxOguVHRBYiibPcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
