---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller

  values:
    fullnameOverride: actions-runner-controller
    flags:
      logLevel: info # debug, info, warn, error
      logFormat: text # json, text
      runnerMaxConcurrentReconciles: 5
      updateStrategy: immediate # immediate, eventual

    replicaCount: 1

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi

    podSecurityContext: {fsGroup: 1000}
    securityContext:
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
