---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret selkies-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: Selkies - User Credentials
        property: username
    - secretKey: password
      remoteRef:
        key: Selkies - User Credentials
        property: password
