---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: selkies-games
spec:
  capacity: {storage: 1Ti}
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: selkies-games
    namespace: games
  csi:
    driver: org.democratic-csi.iscsi
    volumeHandle: tank/ZVOLs/mircea-steamlib
    fsType: ext4
    volumeAttributes:
      node_attach_driver: iscsi
      portal: nas.stor.h.mirceanton.com:3260
      iqn: iqn.2005-10.org.freenas.ctl:mircea-steamlib
      lun: "0"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selkies-games
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: selkies-games
  resources:
    requests: {storage: 1Ti}
