---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-pool-zfs-scrubber
spec:
  schedule: "0 3 * * 0" # Every Sunday at 3 AM

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector: {kubernetes.io/hostname: "home-ops"}
          restartPolicy: Never

          containers:
            - name: zfs-scrubber
              image: ghcr.io/heavybullets8/zfs-scrubber:1.0.9@sha256:2e63ef0fb0f6a34aff2f48faeffd848e6c693a062bb0436f266d02dee717e114
              env:
                - name: "ACTION"
                  value: "scrub"
                - name: "ZFS_POOL"
                  value: "data-pool"
                - name: "PUSHOVER_NOTIFICATION"
                  value: "false"
                - name: "TALOS_VERSION"
                  value: v1.12.4
              securityContext:
                privileged: true
              volumeMounts:
                - name: dev
                  mountPath: /dev/zfs

          volumes:
            - name: dev
              hostPath:
                path: /dev/zfs
