---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name headlamp-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: headlamp
        OIDC_ISSUER_URL: https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab
        OIDC_SCOPES: "openid email profile"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"

  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: Headlamp - Keycloak
        property: keycloak_client_secret
