---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb
  namespace: flux-system
  labels:
    patching.home.mirceanton.com/source-ref: true
    patching.home.mirceanton.com/intervals: true
    patching.home.mirceanton.com/post-build: false
    patching.home.mirceanton.com/decryption: false
spec:
  path: kubernetes/infra-cluster/apps/loadbalancer-system/metallb/app
  targetNamespace: loadbalancer-system
  prune: true
  dependsOn: []
