[MKTXP]
    listen = '0.0.0.0:49090'
    socket_timeout = 2
    verbose_mode = True

    initial_delay_on_failure = 120
    max_delay_on_failure = 900
    delay_inc_div = 5

    bandwidth = False

    fetch_routers_in_parallel = True
    max_worker_threads = 5
    max_scrape_duration = 20
    total_max_scrape_duration = 30

    persistent_router_connection_pool = True
    persistent_dhcp_cache = True
    compact_default_conf_values = False
    prometheus_headers_deduplication = False

    probe_connection_pool = True
    probe_connection_pool_ttl = 300
    probe_connection_pool_max_size = 128
