apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-config
stringData:
    gmail_address: ENC[AES256_GCM,data:T/XzJM/LnwdAB9iNwx6dhV3hpU6eNQhYmH+3Kw==,iv:PzTZk0vJyzaJ8anmLudPR8NuOW+/kQk/xze6+wpsAgk=,tag:EcNNhZqvd35qU1bv9GgcRQ==,type:str]
    mirceanton_discord_txt: ENC[AES256_GCM,data:QY+0rABGzJEsJNqHh0mACVSOmGJ6gRBqsSa2eU2ov1ZBEU/FSxVCUKhWcA==,iv:d4uNdfsjP60TY6MVE2GjzztFk7+ZLOGslmzqlPJYxJY=,tag:AioiDdxYCKyqhPldZdnuEA==,type:str]
    mirceanton_brevo_code: ENC[AES256_GCM,data:fJTKWIXHyS9+Xbdx9nyG2+vCI7vTPqUKG8D63I5+ieONRnPfrzwEFE8p0g==,iv:IxO3xlnMkiwWrc6jhTn7G2S52ky6P1sRK3/4CwqHLkA=,tag:XNtqHDz3zWaGXhgTUIdjSA==,type:str]
    mirceanton_brevo_dkim: ENC[AES256_GCM,data:EUxzyUSZZl1H1D2k2/6rWd/EQCpWdfbzHMCGdkMEdT8Xq/PEWbvOI+yTDDZLzKK+d16rApBhZQzJbFd676qNIrDx9T6rOLDY5h+NR8rnMIwbprn8KSILcOENhh96co/41O8TJXn/KFs3GK3cKA+Tfc7upEx3M5m5J8uqUDW6FZothHr/rxoHbio+GbdrJEATGcrM8iDLZkzVT4FDY8lqFD/XMNQDVKWr5F29RV5rhyv9voBCNvk6jdCEpB4seXZmQ8ZxJX4IrRu+RevZhC34LuNpUEllGAGhkpb6gW+Dahk=,iv:CVi5B0Q1Azo1vdU2BcOAaynZg8hw20nl8VubucIsLr4=,tag:sn0WzWa4kRG/fYRCt5kGiA==,type:str]
    mirceanton_dmarc: ENC[AES256_GCM,data:N/ZdyXJoNk3iVqB+DxbSF4vUtCPrRWlkyfmZork3J4HoUhduzXLtC0a9OIp7OaiFh/SFv3WvhFFLXtK2Wd8m6CNI1rQmBFiGLmSXErxevaKyEi74kWlYYz/2dg==,iv:v5IPF13g3B/D6qB0+fDX2lJ3aJHVUN2YbyWzOQzyulw=,tag:nrH0AORv5opW4R3XviT8Vw==,type:str]
    mirceaanton_dmarc: ENC[AES256_GCM,data:ouz+1Encl/mnsOs68f41xOI9AZOUD+HacFRoOmrIdpg8S61jpJQtQqqZgsvN36q05/eCXUJwwOJ1LfnJZbrGAFLEt8+WY4IWGhkri5QMnzovOXH4SuEqBOo8VQ==,iv:59UOiEV74tBm6m8CbH//T+9e+8qz0NXYRIoSpitNvns=,tag:XZhtComRQQq1O/dvrzbbyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaFZtYjZOS3F2amEzSmF0
            MVVVY25GQXBUWXEzNWx0Mkw4d09BaFZrREQwCmJ5N3JMVXk0R0wzTFZITURHVDBZ
            a0p3bUtubHpYcm5jV2JLeXN5UzJIRzAKLS0tIHR6cXFPZVFSeUJYTXNyNkI2NFNn
            U09QUWgvVWJRVlNDbXA4ZlhGdXNNeHcKA90+Iq7gsg9ZizjF3y++uwUwF/tD+gUm
            4qAT8X5y4NrvKBokfUT8xKLav5PVWTzkLEWhxTFdhXMxVRlc08Ov1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:54Z"
    mac: ENC[AES256_GCM,data:E6eYLskQAqvRIVhJJT/M2PpC6/LCIrJnMJrNSRsehfZzuyQgDSLU2wrVkDvAlD0Fz/00oqkp1evH4h9YIGjRbbBFVpudVWPD3EILEnECYSZ3hUaMDUr2kMtVkUkjtP70TM5WAY7AoPh6wZuwaOAwd480Mbyq7fI0etkjs4DVcHw=,iv:JGFEz0k3yyt9i1AQibC2rnwH0bXllZYDH58RJWWW5nM=,tag:0790DEqKBnuRLjP15MnnIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
