---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-oidc-secret"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: "${APP}-oidc-secret"
    creationPolicy: Owner

  data:
    - secretKey: client-secret
      remoteRef:
        key: "${OIDC_OP_ITEM}"
        property: keycloak_client_secret
