apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-creds
stringData:
    postgres-password: ENC[AES256_GCM,data:Q34K1EmXb7fO04EWWxOzo5mUW84tw7fPfpWS55Y2I6s=,iv:96vaSCEDynk96WNmsyMkDtBMGVlGqTvGcw7QWAKON6Q=,tag:uD1nzaS9yHoGvFt2LZLjwQ==,type:str]
    password: ENC[AES256_GCM,data:RbG1kkuEKsLtZfxliO4MgTdhQNNBisiMEDxg2uSe4w0=,iv:4GZFZqr+ggM1U+O2KXDKj1U4oxJJwEkUSHwBvMGGNF8=,tag:5ejy78WViiXFyT2OAHcCQw==,type:str]
    replication-password: ENC[AES256_GCM,data:LEJF4waELu/DeZ1L50XOiCwmNiRYv0Il/mD7lsBVc64=,iv:XKYrzJcB//VT+OTKDiMbtuYexu1P7iyV0Qz+cc3hN1Q=,tag:PsDHTeQ45FyBB5Fq46NFUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdURGK05JYXJzS0g3aUNI
            WjNCK2tXcU8yanNaMXU2alVVNUVvTm1YV0ZzCjRsRjF4Z0JSN2hnVnVadldkdnNH
            M3dTNW5Ba2tuR3VzQ0xCUlIzUlFmNDAKLS0tIFNvQ0R1YW1HRnZXTjg1UVluSnJv
            R0l1ME1VNnZERy9XYjROM3ZxR2FXTHcK+Vn4On3bcosFdJ+pO5Nkw+fixqbDtQiq
            C8MB1MtQx+PDsGTpHTomY2Z+mkzRJIZBpsqg/RYgdoybJ9UdZHyTBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:57Z"
    mac: ENC[AES256_GCM,data:m2jEJNiOh2gJThMIxPHpFYjvR1scPfBc7Y7R9VgWCDjBy5ofz1a1WbvVBp3o4ElErFNboh6+Tk5lD2VXE2Jm71YZDQV69RkBAjIot/NG4HnILbxslmHw2vw1wUXy4+8Dl1h6dCpiELwSoPcW7ojJXAcdsTgC79CQNFUDTkbYnN4=,iv:4eL6Io/0Ikx9MZi5GICZ9GsKgYEfveAIRaKaZEW2XHA=,tag:2i2s8AMBf1oDWdHHl3RLIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
