[agent]
  interval = "60s"
  round_interval = true
  flush_interval = "15s"
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto.home-automation.svc.cluster.local:1883"]
  topics = ["zigbee2mqtt/+"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  data_format = "json"
  name_override = "home_plug"
  fieldinclude = ["power", "energy", "voltage", "current"]
  topic_tag = ""

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "zigbee2mqtt/+"
    tags = "_/plug"

[[processors.rename]]
  [[processors.rename.replace]]
    field = "power"
    dest = "power_watt"
  [[processors.rename.replace]]
    field = "energy"
    dest = "energy_kwh"
  [[processors.rename.replace]]
    field = "voltage"
    dest = "voltage_volt"
  [[processors.rename.replace]]
    field = "current"
    dest = "current_ampere"

[[processors.strings]]
  [[processors.strings.lowercase]]
    tag = "plug"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
