apiVersion: v1
kind: Secret
metadata:
    name: grimmory-secret
stringData:
    mariadb_password: ENC[AES256_GCM,data:XhFeqrFA0RFRak0Ek+2yKYCl+bLY5515jbqyuC6+qO8=,iv:YXycjCXY8hSW2redJHav5U+TeWJ98eNkljwhjGT+qPg=,tag:hgeXLVqOgCR1W4s5Ctcsyw==,type:str]
    mariadb_root_password: ENC[AES256_GCM,data:hAQ0SC1rOXHo35DKYyYBi1e9XCAlfA7JGZeiO60=,iv:w9kxxwphy4Q9A3nnjjfIdMPJdBjXeQ439H/+NU7iIz4=,tag:Jio/vCkj2fEPiSkch+a5ww==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVjdPN2tiUHhpaXBVNUZw
            bGpkZmEwampVeEN1aWVlT1pDWUFxSWtxMUJnCmkzVWZ4aEVxQjZueGp1MVBCeW1S
            UEdpVi9ad1VzNEIyVGJaQWtyNDBQU00KLS0tIFNKVGh3Z1p4TTd4VFFES1l0NWZQ
            SzJOSG94V3k1RGRxTUFqek1TZk03V28KgTjC8Hs2WjL/I2ZXpO2mpw4sra2otSs4
            5piGHK8VwG1ebfwOpKbkk/JQG4Av2tDq3Z8qwbkh40A1l1dsjKOkmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T18:24:04Z"
    mac: ENC[AES256_GCM,data:HNjgn4pbI4nzrk59yx8DAs0OMvjTcYHFqATEyBea7+/zlx7IdyqwVsOPiJ8LqI6jg3iLSl3liiPtjpWIVG49nVcObkSlEFx+hh9yRhKjlI1byfJAVYXv6oVYB6Q83Fh6dOlcILxLAWNoWGn+u1mnCmM00jGRxKIWy9XydTPffU8=,iv:wf+g8JptwZonx9fhCCX5ksfS4Nt1SuL6bFL0c2ASEBo=,tag:wvqOnarFUdouSxvah/on/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
