---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grimmory
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grimmory

  dependsOn:
    - name: grimmory-mariadb

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      grimmory:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          wait-for-mariadb:
            image:
              repository: ghcr.io/wait4x/wait4x
              tag: 3.6.0
            args: ["mysql", "grimmory:$(DB_PASSWORD)@tcp(grimmory-mariadb:3306)/grimmory"]
            env:
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: mariadb_password

        containers:
          grimmory:
            image:
              repository: ghcr.io/grimmory-tools/grimmory
              tag: v3.2.1
            env:
              USER_ID: "568"
              GROUP_ID: "568"
              DISK_TYPE: NETWORK
              DATABASE_URL: jdbc:mariadb://grimmory-mariadb:3306/grimmory
              DATABASE_USERNAME: grimmory
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: mariadb_password
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: 6060
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: 6060
                  failureThreshold: 10
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 2Gi
            securityContext:
              readOnlyRootFilesystem: false

    service:
      app:
        ports:
          http:
            port: 6060

    route:
      home:
        hostnames: ["grimmory.home.mirceanton.com", "books.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      data:
        existingClaim: ${APP}
        advancedMounts:
          grimmory:
            grimmory:
              - path: /app/data
      books:
        type: nfs
        server: nas.stor.h.mirceanton.com
        path: /mnt/tank/Media/Books
        advancedMounts:
          grimmory:
            grimmory:
              - path: /books

      bookdrop:
        type: emptyDir
        advancedMounts:
          grimmory:
            grimmory:
              - path: /bookdrop
      tmpfs:
        type: emptyDir
        medium: Memory
        sizeLimit: 100Mi
        advancedMounts:
          grimmory:
            grimmory:
              - path: /tmp
