---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-system

resources:
  - ./namespace.yaml

  # Monitoring Stack
  - ./kube-prometheus-stack
  - ./grafana

  # Exporters
  - ./ipmi-exporter
  - ./mikrotik-exporter
  - ./zfs-exporter
