---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: krr-pem
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: krr-pem

  data:
    - secretKey: private_key_pem
      remoteRef:
        key: Renovate Operator - GitHub App PEM
        property: key

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: krr-github-token
spec:
  appID: "900136"
  installID: "53131225"
  auth:
    privateKey:
      secretRef:
        name: krr-pem
        key: private_key_pem

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: krr
spec:
  refreshInterval: 1h

  target:
    name: krr
    template:
      type: Opaque
      engineVersion: v2
      data:
        GH_TOKEN: "{{ .token }}"

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: krr-github-token
