---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hermes-alertmanager
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: hermes-alertmanager

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      hermes-alertmanager:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532

        containers:
          app:
            image:
              repository: ghcr.io/mirceanton/hermes-alertmanager
              tag: v0.1.1
            env:
              HERMES_PORT: &port "8080"
              HERMES_DB_DRIVER: sqlite
              HERMES_CONFIG_PATH: /data/hermes-alertmanager.db
              HERMES_AGENT_WEBHOOK_URL: http://hermes.ai.svc.cluster.local:8644/webhooks/alertmanager
              HERMES_AGENT_WEBHOOK_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: hermes-alertmanager-secret
                    key: WEBHOOK_SECRET

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      hermes-alertmanager:
        ports: { http: { port: *port } }

    route:
      home:
        hostnames: ["hermes-alertmanager.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
