---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-grafana-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: mcp-grafana-secret
    creationPolicy: Owner

  data:
    - secretKey: GRAFANA_AUTH
      remoteRef:
        key: Grafana MCP
        property: service_account_token
