---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ./namespace.yaml
  - ./grafana-folder.yaml
  - ./flux-operator
  - ./flux-instance
  - ./flux-mcp
  - ./headlamp
