---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ci-home-ops-runners
  namespace: flux-system
  labels:
    home-ops.mirceanton.com/group: ci-apps
spec:
  path: kubernetes/home-cluster/apps/ci-home-ops/home-ops-runners
  sourceRef:
    kind: GitRepository
    name: home-ops-git-repo

  targetNamespace: github-actions-runners
  dependsOn:
    - name: cluster-apps-github-actions-controller

  wait: true
  prune: true
  interval: 5m
  timeout: 30m
