---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: services-pool
spec:
  autoAssign: false
  addresses:
    - 10.0.10.250/32 # envoy-services
    - 10.0.10.251/32 # davinci-postgres
    - 10.0.10.252/32 # mosquitto
    - 10.0.10.253/32 # minecraft-router
    - 10.0.10.254/32 # steam-headless

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: admin-pool
spec:
  autoAssign: false
  addresses:
    - "10.0.0.250/32" # envoy-admin
