---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/metallb.io/l2advertisement_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
spec:
  ipAddressPools:
    - services-pool
    - admin-pool
