---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app litellm
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 15m
  targetNamespace: ai

  path: ./apps/ai/litellm/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app

  dependsOn:
    - name: cloudnative-pg-operator
      namespace: database-system
    - name: 1password-connect
      namespace: security-system
    - name: ollama
      namespace: ai
