---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./pvc.yaml
  - ./mgt-deployment.yaml
  - ./detect-deployment.yaml
  - ./luigi-deployment.yaml
  - ./fvm-deployment.yaml
  - ./chaos-deployment.yaml
  - ./tengine-deployment.yaml
  - ./service.yaml
  - ./http-route.yaml
