---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: openebs-zfs
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
