---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ai-secrets
  namespace: productivity
spec:
  provider:
    kubernetes:
      remoteNamespace: ai
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: external-secrets
