---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |-
          {"openid_connect":{"APPS":[{"provider_id":"keycloak","name":"Keycloak","client_id":"paperless","secret":"{{ .KEYCLOAK_CLIENT_SECRET }}","settings":{"server_url":"https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab/.well-known/openid-configuration"}}]}}

  data:
    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: Paperless-NGX
        property: username

    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: Paperless-NGX
        property: password

    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: Paperless-NGX
        property: secret_key

    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: Paperless-NGX - Keycloak
        property: keycloak_client_secret
