apiVersion: v1
kind: Secret
metadata:
    name: op-token
stringData:
    token: ENC[AES256_GCM,data:b/JRwuhQHbhyL+ce5Knth/LVoBsvvFXJPauS6c0vSBwrl8pJ+ThHJ23TwuE+jFQisDfkqi0Cmi8Zd7GlSkQ1rV7HsSBpMCkjWov4dyI4saipgbaq/260Lk2u3ydJaTrBO3TosxLKyg0+vDkQWaapFtvGu/dqYq3QdUSEx8PwMo4YU+6kKyp+Vp4WvF0QtS4+wWsYUIpqyJR9U1VqUPsPDNezLJh1oWJFy+l/uIbw/ZYA+lYKDs4sKMdbgqpbEBcp5tQs16+KBKlg+P8fkG+0XscOY5U4y0jdXfk9fmt7NwbtBKN486R57dSYAWImFfgFe4b7p02l9HflbZW8/4c2NIuNzZwcr46nGqkQol/GpocY3XulUlSyjTTlH924V59Spee8Zgpft7GgprXX9/Kp2j0wiDvOcjHX8rSY0NJLAwpIVkNE1JRtO+XdLGoxQQm91qrexhpqMoDgXM3ofvFziIJRzcg4Hrc2uAfabSpXSdUh9WChsIXQ70oXjiMBg8ywdO/jXT+Wkx1H2ko+zzXGiSCMnMwg9H89NXlNFWmd2KhRpFAlUOwesSMx+mu1jy8Wg2lhENSR10FrRW1JOwXS8LtQu0IC51tyATt3MEoBSvQuzQ2Astu7tMeoRb3ke/laqFIjbPUYOx1+RiFn6HB0z7VZ8kggGJRRJO1H9nXixeTlPjwWieHAm7lT5+wyPcmK9g/V3hc4WckD0BDkRadTqlrWsBvsTTKILsc9jrP6c9BOFdxnzV2DeEfpyKxrdUD+FVTmlq3tuCluMN+mjJkCJVDN/uEaT/4+zHllEifLFG2LG9TtYMIehkFyNi4YijC1yux5+QmmhH9oQifau5Emohjq+9K0B8R9ycm9cTGQEtwC8zUNaOEyhe6irBYnKAerwgSopF4EibefROm4ln1Eoe8bQEdcZBSVp0hzPNL9bTzbZ9vENDT+0EkyGQQFxCNEtNfA7L9cLrY60L7fbiXWxhDamLIZIl2dAfxZI9bmIXL+14I=,iv:v21OU1YuFgCig8LEIP5WZhe9kObXDW3SIfindP0P8dE=,tag:VJHUq0gkc4CdAfKFkzOX9w==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTG5nUkIzWGp1cnhSekta
            WjF5QWhCOVZERGxDd2FSNzZuYUpoSEdRQUd3CmVlQzZrUzZoMFpORmFiT09qOXVk
            RkRkYXEzUTJiNzkrN3JwY3oyNHhzQmsKLS0tIE55TzZ2MWdDbU1XeDJtbG9Ybm91
            NXZiNE9zYUdXTmV2Nmc5QzUzalV4WUUK8lNKokZ4124zQcixQl8E4rWLihPY7x7Q
            g1F9WOny1Gbn4IRd1dHjN0dm7e36X1P2Lzrc+grb4zZCku1a+0lmhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T00:24:53Z"
    mac: ENC[AES256_GCM,data:UO595xxMNLCq3Qbj5cto51O0bNQP1kdeELMiOhtEO9/RBgA1rhsOCp04i4LV/pnlXJ99Uhs68ubcCijhAOMOuZNGUr2+gvbC3U9RTVQkj7wNoEMOWEW8cfxk5uR73+ldc3mWVfBst1q4UNGT/vdNjdB7QDNTMUxymhEDWD/aKcY=,iv:XaEdrmFCBVzjbHqg1DgV+0buyPcfSSSNOv4t4gvdQL0=,tag:twSPun52FMXkoSiTe0+NHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
