---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-router
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: mc-router

  values:
    fullnameOverride: minecraft-router

    image:
      repository: ghcr.io/itzg/mc-router
      tag: 1.45.0@sha256:7b4e7117e0ca96aa05dd6c3a9774e4a17ac6e5e61284bab7e108823d3c1cce68
      pullPolicy: IfNotPresent
    extraArgs: ["--in-kube-cluster"]

    minecraftRouter:
      autoScale:
        up: { enabled: true }
        down:
          enabled: true
          after: "30m"

    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 512Mi

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      privileged: false
      capabilities: { drop: ["ALL"] }

    services:
      api:
        type: ClusterIP
        port: 8080
      minecraft:
        type: LoadBalancer
        port: 25565
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.0.10.253
          external-dns.alpha.kubernetes.io/hostname: badoink-mc.home.mirceanton.com
