---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-router
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: mc-router

  values:
    fullnameOverride: minecraft-router

    image:
      repository: ghcr.io/itzg/mc-router
      tag: 1.43.0@sha256:1a7bdbd02f30f53381277eafa16bea72b97f2b5c87c28712491a1a385023aa09
      pullPolicy: IfNotPresent
    extraArgs: ["--in-kube-cluster"]

    minecraftRouter:
      autoScale:
        up: { enabled: true }
        down:
          enabled: true
          after: "30m"

    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 512Mi

    podSecurityContext:
      fsGroup: 1000
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop: ["ALL"]

    services:
      api:
        type: ClusterIP
        port: 8080
      minecraft:
        type: LoadBalancer
        port: 25565
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.0.10.253
          external-dns.alpha.kubernetes.io/hostname: badoink-mc.home.mirceanton.com
