---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: navidrome

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      navidrome:
        containers:
          navidrome:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.63.2
            env:
              ND_DATAFOLDER: /data
              ND_ENABLEDOWNLOADS: "true"
              ND_ENABLEEXTERNALSERVICES: "false"
              ND_ENABLESHARING: "false"
              ND_ENABLESTARRATING: "false"
              ND_LOGLEVEL: info
              ND_MUSICFOLDER: /music
              ND_PORT: &port 4533
              ND_SCANSCHEDULE: 30m
              ND_AUTHREQUESTLIMIT: "0"
              ND_PROMETHEUS_ENABLED: "true"
              ND_PROMETHEUS_METRICSPATH: "/metrics"
              # ND_BASEURL: https://navidrome.home.mirceanton.com

            resources:
              requests:
                cpu: 20m
                memory: 512Mi
              limits:
                memory: 2Gi

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        ports:
          http:
            port: *port

    serviceMonitor:
      navidrome:
        serviceName: navidrome
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 15s
            scrapeTimeout: 5s

    route:
      home:
        hostnames: ["navidrome.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /data
      music:
        type: nfs
        server: nas.stor.h.mirceanton.com
        path: /mnt/tank/Media/Music
        globalMounts:
          - path: /music
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /config/cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
