---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app convertx
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 15m
  targetNamespace: default

  path: ./apps/default/convertx/app
  components:
    - ../../../../components/volsync/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi

  decryption: { provider: sops }
  dependsOn:
    - name: external-secrets-operator
      namespace: security-system
    - name: openebs
      namespace: storage-system
    - name: volsync
      namespace: storage-system
