---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ipmi-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: ipmi-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        key: "IPMI - metrics"
        property: username
    - secretKey: password
      remoteRef:
        key: "IPMI - metrics"
        property: password
