---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ipmi-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ipmi-exporter

  values:
    controllers:
      ipmi-exporter:
        containers:
          ipmi-exporter:
            image:
              repository: quay.io/prometheuscommunity/ipmi-exporter
              tag: v1.10.1
            args:
              - "--config.file"
              - "/config.yml"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 128Mi

    service:
      ipmi-exporter:
        ports:
          http:
            port: 9290

    persistence:
      config:
        type: secret
        name: ipmi-credentials
        globalMounts:
          - path: /config.yml
            subPath: config.yml
