---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: feishin
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: feishin

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      feishin:
        containers:
          feishin:
            image:
              repository: ghcr.io/jeffvli/feishin
              tag: 1.15.0
            env:
              SERVER_LOCK: true
              SERVER_NAME: Navidrome
              SERVER_TYPE: navidrome
              SERVER_URL: https://navidrome.home.mirceanton.com
              ANALYTICS_DISABLED: true
              LEGACY_AUTHENTICATION: false
              TZ: Europe/Bucharest

            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 32Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        ports:
          http:
            port: 9180

    route:
      home:
        hostnames: ["feishin.home.mirceanton.com", "music.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      writable:
        type: emptyDir
        advancedMounts:
          feishin:
            feishin:
              - path: /var/cache/nginx
                subPath: cache
              - path: /var/run
                subPath: run
              - path: /var/log/nginx
                subPath: logs
              - path: /etc/nginx/conf.d
                subPath: nginx-conf
              - path: /tmp
                subPath: tmp
