---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: pushover
    groupBy: [alertname, namespace]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: pushover-silent
        matchers:
          - name: alertname
            value: TargetDown
          - name: job
            value: node-exporter

      - receiver: pushover-silent
        matchers:
          - name: severity
            value: info

      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor

      - receiver: "null"
        matchers:
          - name: alertname
            value: Watchdog

  inhibitRules:
    - sourceMatch:
        - name: alertname
          value: InfoInhibitor
      targetMatch:
        - name: severity
          value: info
      equal:
        - namespace

  receivers:
    - name: "null"
    - name: pushover-silent
      pushoverConfigs:
        - userKey:
            name: alertmanager-pushover-secret
            key: user-key
          token:
            name: alertmanager-pushover-secret
            key: token
          title: '{{ template "pushover.default.title" . }}'
          message: '{{ template "pushover.default.message" . }}'
          url: '{{ template "pushover.default.url" . }}'
          priority: "-1"
          sound: none
    - name: pushover
      pushoverConfigs:
        - userKey:
            name: alertmanager-pushover-secret
            key: user-key
          token:
            name: alertmanager-pushover-secret
            key: token
          title: '{{ template "pushover.default.title" . }}'
          message: '{{ template "pushover.default.message" . }}'
          url: '{{ template "pushover.default.url" . }}'
          priority: "0"
          sound: gamelan
