---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack

  values:
    crds: { enabled: true }
    cleanPrometheusOperatorObjectNames: true

    defaultRules:
      disabled:
        NodeMemoryHighUtilization: true

    # ==========================================================================
    # Alertmanager
    # ==========================================================================
    alertmanager:
      enabled: true

      route:
        main:
          enabled: true
          hostnames: ["alertmanager.admin.mirceanton.com"]
          parentRefs:
            - name: envoy-admin
              namespace: network-system

      alertmanagerSpec:
        alertmanagerConfiguration: { name: alertmanager }
        # =======================================
        # App Settings
        # =======================================
        externalUrl: "https://alertmanager.admin.mirceanton.com"
        logFormat: json
        logLevel: info

        # =======================================
        # Resources
        # =======================================
        replicas: 1
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            memory: 128Mi
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-zfs-cache
              resources:
                requests:
                  storage: 1Gi

    # ==========================================================================
    # Prometheus Operator
    # ==========================================================================
    prometheusOperator:
      enabled: true
      # =======================================
      # App Settings
      # =======================================
      logFormat: json
      logLevel: info

      # =======================================
      # Resources
      # =======================================
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          memory: 128Mi

      prometheusConfigReloader:
        resources:
          requests:
            cpu: 5m
            memory: 32M
          limits:
            memory: 32M

    # ==========================================================================
    # Prometheus
    # ==========================================================================
    prometheus:
      enabled: true
      route:
        main:
          enabled: true
          hostnames: ["prometheus.admin.mirceanton.com"]
          parentRefs:
            - name: envoy-admin
              namespace: network-system

      prometheusSpec:
        # =======================================
        # App Settings
        # =======================================
        externalUrl: "https://prometheus.admin.mirceanton.com"
        enableAdminAPI: true
        retention: 90d
        retentionSize: 200GB
        logLevel: info
        logFormat: json

        # =======================================
        #? Replace default Prometheus image with prompp and
        #? override 'unsupported Prometheus version' error
        # =======================================
        version: v2.55.1
        image:
          registry: mirror.gcr.io
          repository: prompp/prompp
          tag: 0.8.0

        # =======================================
        # Security
        # =======================================
        securityContext:
          runAsNonRoot: true
          runAsUser: 64535
          runAsGroup: 64535
          fsGroup: 64535

        # =======================================
        #? Disable prometheus resource to be created with selectors based on
        #? values in the helm deployment if a nil or {} value is provided
        # =======================================
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false

        # =======================================
        # Resources
        # =======================================
        replicas: 1
        shards: 1
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-zfs-cache
              resources:
                requests:
                  storage: 200Gi

    # ==========================================================================
    # Grafana
    # ==========================================================================
    grafana:
      enabled: false
      forceDeployDashboards: false
      operator:
        dashboardsConfigMapRefEnabled: true
        folder: monitoring-system
        matchLabels:
          grafana.internal/instance: grafana

    # ==========================================================================
    # Exporters
    # ==========================================================================
    nodeExporter: { enabled: false }
    kubeStateMetrics: { enabled: false }
    kubeControllerManager: { enabled: true }
    kubeScheduler: { enabled: false }
    kubeProxy: { enabled: false }
    kubeEtcd:
      enabled: true
      endpoints: [10.0.0.15]
      serviceMonitor: { scheme: http }
    coreDns: { enabled: true }
    kubelet: { enabled: true }
    kubeApiServer: { enabled: true }
