apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    foo: ENC[AES256_GCM,data:K4Eg,iv:lOSBdjiAt9qZEAxN29Du9QEqnU6GLPNUNfMjxw9fJM8=,tag:rKSR2C7lRLhhNjewWrj7jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacW1NbkhMOUNLYWxEMlo3
            eFBMblQwTlVHeVdaVXlUSS9qcHNuTS9Ec3kwCjd2dkxKMEhVSmg2cEpIaXBsb1Bh
            cTNjQmRQOU42TUlEK3dDVDJsYnAveFUKLS0tIGxZSG1Ic1oyVlpxMS9WL2QvcWRp
            OC8xZUt0Qm96akQ2V2ZjUHR0RDByZVUKb+vv5xGZXPh0P7k8kyEfHlIQ70mPzxgy
            VjeMQlpvLXEThlexylcN5DUuWS4NAS719oNjv9puLxdl8SI4fwLtug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:54Z"
    mac: ENC[AES256_GCM,data:FI2zwwudDcsdJI9Ti5m2DU6FJ0GVW3Iecf1hoLfbyaFU7gsecDjDHVwbnHNzllK8I5IFvpPNN+cKHaZOh7/JYEcoPjDxzGfQ7fWd98bVOgZbGNOgE9A861BknwZfBiPtJyCzzckflCnSDNScptKuZwP38wMbg2+8boRw1glPY7c=,iv:ReYTCsPkm0R2F3lbcH0weTME3+e1pXWFVZUzqvL/Kqg=,tag:NcjTd9Ud2MkOJfG9EZFB0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
