---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_ID: "0"
  CLUSTER_NAME: infra-cluster
  CLUSTER_DOMAIN: infra.mirceanton.com
  CLUSTER_ENVIRONMENT: production # staging, production -> selects letsencrypt cluster issuer
  CLUSTER_APPS_BASE_DIR: ./kubernetes/infra-cluster/apps

  INGRESS_POOL: 10.0.10.90-10.0.10.90

  TIMEZONE: Europe/Bucharest
