---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_DOMAIN: infra.mirceanton.com
  CLUSTER_ENVIRONMENT: production # staging, production -> selects letsencrypt cluster issuer
  INGRESS_POOL: 10.0.10.90-10.0.10.90
