---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: telegraf-ha-plugs
spec:
  staticConfigs:
    - targets:
        - telegraf.home-automation.svc.cluster.local:9273
      labels:
        job: telegraf-ha-plugs
  metricsPath: /metrics
  scrapeInterval: 30s
  scrapeTimeout: 10s
