---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr-exporter-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: lidarr-exporter-secret
    creationPolicy: Owner

  data:
    - secretKey: api_key
      remoteRef:
        key: Lidarr API Key
        property: password
