---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: firefly-mcp
spec:
  proxyRef: litellm
  proxyNamespace: ai

  alias: firefly
  url: http://firefly-mcp.finance.svc.cluster.local:3000
  transport: sse

  authType: bearer_token
  authTokenRef:
    name: firefly-mcp-secret
    key: FIREFLY_MCP_TOKEN
