---
replicaCount: 2

image:
  repository: "ghcr.io/actions/gha-runner-scale-set-controller"
  pullPolicy: IfNotPresent
imagePullSecrets: []

flags:
  logLevel: "debug"  # "debug", "info", "warn", "error"
  logFormat: "text"  # "text", "json"
