apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    labels:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: infra-system
stringData:
    root-password: ENC[AES256_GCM,data:zWPP/OaKPub0xvesHsnHT+m3pwdQhszkRR5WIP8+x74=,iv:fwGA1doqRc68vDtdQs0G3MHSybVGk+H/wAM2ySJVQW8=,tag:f3+VWFNvAB1tjAVyqPVQRA==,type:str]
    root-user: ENC[AES256_GCM,data:LOjC9DI=,iv:oNKy23fpUAqrlsHvwcRxVv/Cq29qa63KFeHmTJResCU=,tag:O8GdZzNeOBK5pZ6EdGuUyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRK3VaL0VJMjAyYjJYMDhS
            RjdKL0J5NldxZVlkelUwcEdvT3BrM0t4Ylg4CmlVUFU4c2hDWEF1dlREL1RIZ0NI
            TUM3Y21uQStqL3ErT1B1Nk56U2lsOW8KLS0tIEpRcGJ1V3NRaXVCTnFmaUdodVVa
            L2VreTV6R1l2elM0K0VKblFtMjlKRDQKq1Q9VkWHlbm5odDZQGR2+ihUSTua6HFF
            ryCC4QaDEuydLCSjJ13uyrKpNDzLSYID/ZAD8YLtUPPsZs9M1R3qdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:57Z"
    mac: ENC[AES256_GCM,data:0iSrE5yT/th+Xs7Fu5d9w1bX7uhF2AQlniRpwybkrNJSEwR3Y337NWM1j8m/NoxSRGdg+DfKU0lTLlsdQ4q4odmotDBQYIHZwso7MViqu3RTv8b/KjSipPUv4xQJEeP0lRD7x+i4UvwcN1vy7Rz4nHFRmshQm4mH/bTiWPMZ7d4=,iv:2p9LoqQ/0LlgXEVeWnpSMohORgC2LJaJbEf9EYPIJG4=,tag:R0XxJK3zkClYVesvxmh/yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
