apiVersion: v1
kind: Secret
metadata:
    name: minio-creds
    labels:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: terraform-system
stringData:
    root-password: ENC[AES256_GCM,data:6SVj2qVySj3KX4gJADahB6+zdeDVn2fW2zQgkYJCNpw=,iv:31Yerba5wSX3nu4K51oAidn4Wb67IPT/LoKf5ob/ga8=,tag:PuB1CZkjYeU812W5nCP9rw==,type:str]
    root-user: ENC[AES256_GCM,data:qU6VJhc=,iv:LniSxCgPyi+VNPu6JxxbQ8ZEdD0NIh3V1CNaZXtla1w=,tag:sqy1l0fdh1oHYR71NxQvvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a3U0Z0ZvY3lKaldoU2hL
            bEVBYnZjSE9GdEJodFZZNGlPOXl0YVNGd2hZCjVuKy9JQUFrN1Y3Tms3bGY5SDdY
            M1h1YWZaZWo1cnJOZUJzQ1R1Y1FpMDAKLS0tIExJK0FydWdoVXBqSG5ualRTZUNN
            ZEdHTkgrUUQ4Kzk0clR1dWtvSXVhMTQKssisRs/+S9ZFRYrXAcVhs3QuGd9AdnPl
            JyiYd9kYnIrnRsSwPj680EIvMttJkCIo7Sx6kiLqs29TmpwO/ww51Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T23:49:48Z"
    mac: ENC[AES256_GCM,data:PGyni5bEt1we8zJ98L3xPD8g89rbrnAHGMkR7OPU/MQqBUGFyutdwPp9HtS95LFLQe187Q3CEdH2z9bMbg5uYtOfsiIgEPCtpIffQ3Skf28UR4+9MaGhvYaY6EpF0jWHZfli66PgWyRgavjqAYjsr1NatxtMCmKIwSCgFpW3wYo=,iv:/kSAvnJxQ57NB49KJpADTckXX0BGyJNVufQgj/FBLWg=,tag:lh2FCgeaRTbsBWxJUIiuOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
