---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: convertx-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: convertx-secret
    creationPolicy: Owner

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: ConvertX
        property: jwt_secret
