---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stockii
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: stockii

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      stockii:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000

        containers:
          app:
            image:
              repository: ghcr.io/mirceanton/stockii
              tag: v1.9.9
            env:
              STOCKII_PORT: &port "8080"
              STOCKII_CONFIG_PATH: "/config/stockii.db"
              STOCKII_DATA_PATH: "/data"

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      stockii:
        ports: { http: { port: *port } }

    route:
      home:
        hostnames: ["stockii.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      data:
        existingClaim: ${APP}
        advancedMounts:
          stockii:
            app:
              - subPath: data
                path: /data
              - subPath: config
                path: /config
