---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr-exporter
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  targetNamespace: downloads

  path: ./apps/downloads/radarr/exporter
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: 1password-connect
      namespace: security-system
    - name: radarr
