---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: storage-system
spec:
  title: Storage System
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
