# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firefly-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: Firefly Keys
        property: APP_KEY
    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: Firefly Keys
        property: STATIC_CRON_TOKEN
