apiVersion: v1
kind: Secret
metadata:
    name: firefly-data-importer-token
stringData:
    IMPORTER_TOKEN: ENC[AES256_GCM,data:Wq/Iqbxeai7JEAinjn8zrlJIS5pio93DA1kwzBHJHLIp7EZa0UPkR0errlFMj6JJuRIht/cEUEy29lH2duoWkTjryyfbShEAp50J2w79NZHFtUCI3niknKKU7unlm8nhnjvLD+gKfhUuRIVEoV5YaTD9s54GGCmpZ++UPY8mC2ZjiYe62pDDqQwfYBKrhdgXfhRn5FhJqNDxGhUUZqEb0Ng3sFNsq8B0yvbx29Tv4U8/6OXpeOgNbEvoTA74qSlnRaFXfM6+8cgvh5gXvzAx2XZtUW2fB5ReNl42Qolq93ukOsFlx+QKdWkYCjXZms72kwPcJI207SJOY2e/mvkWBWy6U7OTvxgYF5xZXfFJ+qGW+OJRanW0eijqdrgpNw/zmupUAhh7gugo117VoiUFI9+VM+7WDoS7NqqByGgKEd4zgaQwTOz5QAaA50YoYeV5uvHuvsnOlCh5c/z4z3taPGvJagPaU7/8OKif6BKFB2NOh1kmuWfmaxQ6A9wIOnCD/UZvMu7fLxzV4qEei+NTKggkBTT/IdsNqs5SjzckqMDSVgjJisXv+u5gdzPdshLVzjk4bkW10bMqYMWh+hrBliCJoC0sUQUlmynAJufmS0Iu/L77JUWFkMjQfzTDwJevDfmqeT+ZOFwuwsajg2jPKpCuD5XhB+t0KE700fp9tTgwyStioABLCa+IAMCDNmO7XPAQksS5V7eT0dcOtAv5fYiRXmQdRwHG5+e1r8D5WkePxnHQQKuQ/TcfPDEMBl3/2EgoZ6tte9On3CDyJ2MBjT3c8sZfEOsKMDh9iczRj5IJfHLXq2fcg4sQFQ3BUyF3vxTSiisNQEO0ZTPsC2rK5qNI7SDm1pyPFBBs3eAD+8r5FJUbzeObPv4dwNW7CWBVxWEs80NHmKrBeJhnXAA0ynNS9VUImPApOCpcbZOjMTFrGogS3Zj2N/yOnX1vGJSM6LC+v77c7WMZL54LqJHFfuIljDcc0jVM02potRRjnHBYcp0MtfpWfjQB3SNX0deGyy2Us8qNiseGbSAjQX61FximGmgZAc/jDcc7TGa3j95H0xJnNeap1694JIF3+7fSIS+MQYQMErZJGoHkEKi9wo7UHMW4Q9XQfp2X9hvS7obDalzWRGTKj1fpfesJuu67Fgc3EkhLAyCbNBB+2f5iN83VTur+k8Yu/NqRHEvur6kDIDAhta/Bv/7A4mU4FIccyhgJ7A66JamteFdGkWtvzSZRvUTPPGolsN86T1d1tpdOmYodYLleCgIsiDJ1vl3KwqxZAtJyFnRNtC1fQQEUfuY=,iv:hRYRyB83S03TL/lG5VghjZ67PaufQcyVFg+JKOxEujE=,tag:q6Sz5g4iVmbhfs/1Klh2zg==,type:str]
    ACCESS_TOKEN: ENC[AES256_GCM,data:7rn+XJWaJiCtGJgVphnKPCxfCvJeDSBpkauweriNZ7yelx2lwQpN8qgA4qzaqJMTsQ02htdZqm6uKF7EVjIDzg==,iv:cL2IMvcUUWSnaWdFvifmnCa5tbOwLwK+QP6XCFlsOO4=,tag:UC1wTU+LUG+BpLITUZdoxg==,type:str]
sops:
    age:
        - recipient: age1d7fjm42t7d8r9g4glua85tkrf4txswk2hnc8s4pgr8nyupnenfhqmegklw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ampCd1ByV0docGczQldL
            VXpNSWhuckwzd2RhdCtydUQ5RzhQTlFDY1U4CnNxTkZrWnZNWHpjM2NzbzIxeDFC
            ajh3THJyTTV5STVYNXFMOVBFWWVxN2MKLS0tIFU4dWo4cDIrdldLUFpNdTdDZjBC
            VFdpNU5iUG1CdjVBRko3VEErOGFXWU0K3D3m2imy6mvxiV6xbA7XHM2CSooeFD9Z
            TFKpO/aUySbPEnvtUiAl+VKAhNRrAuLayuULTBGldMuVqk3NpODKkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T21:18:23Z"
    mac: ENC[AES256_GCM,data:VkbbttDmSEbU0J1rWcPEfLJoUupK8XYWOKFgwjLOLikCDqSxxWUvvlNH0sQHgOPWSLCs0XUwCoKt4XsUk1t4d9eEMulFAPiO4zHNyuJHoMGKhGGadpOibkQakENiUw3HCAuquWJmhq3ltOrsZ1WUXsPgu2jGJWUVDMmG8lv6Gy4=,iv:ig0/AhlQMJXo9MhwhI9L4kPFG5C4nLn0hlENL9fyYz8=,tag:XwCXzIdwF6LdEAlXuhgzig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
