---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./firefly.oci-repository.yaml
  - ./firefly.helm-release.yaml
  - ./firefly-settings.configmap.yaml
  - ./firefly-keys.secret.sops.yaml
  - ./firefly-data-importer-token.secret.sops.yaml
