---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: speedtest-exporter

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      speedtest-exporter:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          speedtest-exporter:
            image:
              repository: ghcr.io/heathcliff26/speedtest-exporter
              tag: v1.6.2@sha256:5c4899cae36ba7c0f3fcfc47f9564668f7ab7d312780af6108ba5b46445a284b
            env:
              OOKLA_EULA_GDPR: "true"

            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
                add: ["NET_RAW"]

        pod:
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
            fsGroup: 1000
            runAsNonRoot: true

    service:
      speedtest-exporter:
        controller: speedtest-exporter
        ports:
          http:
            port: 8080

    serviceMonitor:
      speedtest-exporter:
        serviceName: speedtest-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 10m
            scrapeTimeout: 5m
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_name]
                targetLabel: instance
            metricRelabelings:
              - sourceLabels: [job]
                targetLabel: job
                replacement: "integrations/speedtest"
              - regex: exported_instance
                action: labeldrop

    persistence:
      cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: openebs-zfs-cache
        advancedMounts:
          speedtest-exporter:
            speedtest-exporter:
              - path: /cache
