apiVersion: v1
kind: Secret
metadata:
    name: keycloak-config-smtp
stringData:
    smtp_host: ENC[AES256_GCM,data:o6Add+JwzXY6k4vz8Y/IN82LyKU=,iv:wPooptHYGRtwzhfHhpQR0+PGs2/B8SFqC94n1gxBBhw=,tag:Kx0T3DZrsctPfg/bXzLHmw==,type:str]
    smtp_port: ENC[AES256_GCM,data:b9VF,iv:hiwIxkI+wjzVCUWD6Vlri6dhJiQFRCD3pOS5mLCsV2c=,tag:Tp8ukXAqgkGyqgFsBmNZNQ==,type:str]
    smtp_user: ENC[AES256_GCM,data:bBSx1Di5ibT7+kSkg0sDHfXu+9mMuPoBPB5Mfw==,iv:+OTxok5XlXviMVZpHAADml5xK+B4Bbk3T9BBMCfnkl0=,tag:ofG1vy911CSLIDGRAuW8JA==,type:str]
    smtp_pass: ENC[AES256_GCM,data:A8MjbIA0J9AjNcBBImY8i/yjJ02KK0OjIdOik0JWc0KYUo8mzqzy6vB4YTVMK9XqLqFHGRHdxcVBm5VmEq7NZRkyGND0ti86bLHhenvSVKwalXitb9b6P1bA,iv:VIKSfbD5h0jPJH54glKCzke45Q1D7+j8c9Jp64l8eGA=,tag:JYxzWrMU4YNUj8kXYI6DtQ==,type:str]
    smtp_starttls: ENC[AES256_GCM,data:XZrJ+bk=,iv:KjU50pWq9L0ZYDFoCUtqVbBOWoM2RCsWJprFpMtedo4=,tag:K8/9LyveY03qVOSX5/up5g==,type:str]
    smtp_ssl: ENC[AES256_GCM,data:654irWM=,iv:n/KIIl84jSy1HL6+3+LgsFn/mJkjwHXCmEI+wIttCSo=,tag:3zhPe25M3fl4idx/UEjNlA==,type:str]
    smtp_from_address: ENC[AES256_GCM,data:v8QHudbsEvIBufABOYUz/VCGe1QdpfPE6NTLJg==,iv:99SnFIl9zlVv4eStYZb2gayS2tYZielZ/XTdtD7usKA=,tag:WfhQU2UeyNgs6OkXksbUhA==,type:str]
    smtp_from_name: ENC[AES256_GCM,data:Hqgw3ShFeCxO1JTm9w==,iv:MIJzxSyyJQ/EOApob5b2WrCgVxd0shnGbUnO+JVYAf0=,tag:SCbFxRtICRJ2EKpf93BuSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQmpMaU5pcTcrVkxESFFN
            djEyK05rR0VCWWxmeHozT2llN21vYXU3WDNFCjNwRUNlc1BiYUtTZjRKNHZkQUha
            emp4MGpZajB0T0tBQVJ0dHVScmk5NFkKLS0tIDJSeTMxVGFTdUwweGdlUDZmODll
            RWdQNC9IRlE3SDdSWWJ6WFo4b3NUQ0EKMrZ3khYsrtIWEsp3532PEKDp66silsE6
            t+i6giIzfDthg+0m0FxkMi6L0Bgt8YgiERkmc2a+JnLIgoWGCoWtMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:57Z"
    mac: ENC[AES256_GCM,data:FrWCfB2vl0qOpenL1b9v8lUnentO3AaN3bx8XkrNGTjl3nHojGV5R2/uvyA0UUAxbm+QFWdAmwdiYj2txRGNcmGt3cWf6wyxY2e9eQGRv48Ta0nLUyQOXKfIg6MVZRtyPrSZMQtxurhcv/q3rlaJzWJoTxggHrW30TMlb4eCizg=,iv:ES7cAmH+YOVotQbdVVnNfmaMYZPzWvpLUQiQeMNJESg=,tag:B6X4Xt/Xl5sXAviOiwdEtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
