---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-bot-autoscaler-config
data:
  services.yaml: |
    ---
    activationWindow: 10m

    services:
      # example-service:
      #   namespace: games
      #   workloadName: example-deployment  # optional; defaults to the map key
      #   workloadKind: Deployment          # required: "Deployment" or "StatefulSet"
      #   activationWindow: 20m             # optional; overrides global default
