---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot-autoscaler-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: discord-bot-autoscaler-secret
    creationPolicy: Owner

  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: Discord Bot Autoscaler
        property: bot_token
    - secretKey: DISCORD_GUILD_ID
      remoteRef:
        key: Discord Bot Autoscaler
        property: guild_id
