---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache
spec:
  storageClassName: openebs-zfs-cache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
