---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-tailscale
spec:
  logging:
    level:
      default: info

  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
      envoyService:
        loadBalancerClass: "tailscale"

  shutdown:
    drainTimeout: 180s
