---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: metallb

  values:
    crds: {enabled: true}
    networkpolicies: {enabled: false}

    # =============================================================================================
    # Component - Controller
    # =============================================================================================
    controller:
      enabled: true
      logLevel: info # all, debug, info, warn, error
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 256Mi

    # =============================================================================================
    # Component - Speaker
    # =============================================================================================
    speaker:
      enabled: true
      logLevel: info # all, debug, info, warn, error

      tolerateMaster: true #? allow scheduling on master nodes
      ignoreExcludeLB: true #? ignore the exclude-from-external-loadbalancer label

      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 256Mi

      frr:
        resources:
          requests:
            cpu: 10m
            memory: 51Mi
          limits:
            memory: 51Mi

      reloader:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 32Mi

      frrMetrics:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 32Mi
