---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: metallb

  values:
    crds: {enabled: true}
    networkpolicies: {enabled: false}

    # =============================================================================================
    # Component - Controller
    # =============================================================================================
    controller:
      enabled: true
      logLevel: info # all, debug, info, warn, error
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 256Mi

    # =============================================================================================
    # Component - Speaker
    # =============================================================================================
    speaker:
      enabled: true
      logLevel: info # all, debug, info, warn, error

      tolerateMaster: true #? allow scheduling on master nodes
      ignoreExcludeLB: true #? ignore the exclude-from-external-loadbalancer label

      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 256Mi

    # =============================================================================================
    # Monitoring
    # =============================================================================================
    prometheus:
      serviceMonitor: {enabled: true}
      serviceAccount: "metallb-prometheus"
      prometheusRule:
        enabled: true
        bgpSessionDown: {enabled: false}
        staleConfig: {enabled: true}
        addressPoolExhausted: {enabled: true}
        addressPoolUsage:
          enabled: true
          # Exclude the pools matching the regular expression from triggering the alert.
          excludePools: ""
          thresholds:
            - percent: 75
              labels:
                severity: warning
            - percent: 85
              labels:
                severity: warning
            - percent: 95
              labels:
                severity: critical
