---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-runners
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set

  values:
    githubConfigUrl: https://github.com/mirceanton
    githubConfigSecret: github-org-token
    minRunners: 1
    maxRunners: 10

    controllerServiceAccount:
      name: actions-runner-controller
      namespace: github-actions

    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: openebs-zfs-cache
        resources:
          requests:
            storage: 4Gi

    # listenerTemplate is the PodSpec for each listener Pod
    # For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
    listenerTemplate:
      spec:
        containers:
          - name: listener
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 20m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 64Mi

    template:
      spec:
        securityContext:
          fsGroup: 1000
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: runner
            image: ghcr.io/mirceanton/actions-runner:2.336.0@sha256:0b0f18a3ed409fcc86911a4d9149d3e2554454819d778510683c7e41d8984681
            command: ["/home/runner/run.sh"]
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            env:
              - name: PIP_CACHE_DIR
                value: /cache/pip
              - name: NPM_CONFIG_CACHE
                value: /cache/npm
              - name: MISE_CACHE_DIR
                value: /cache/mise
              - name: MISE_GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: github-mise-token
                    key: github_token

              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP

            volumeMounts:
              - name: cache
                mountPath: /cache

            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 4000m
                memory: 4Gi

        volumes:
          - name: cache
            persistentVolumeClaim:
              claimName: github-runners-cache
