---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: searxng-secret
    creationPolicy: Owner

  data:
    - secretKey: secret_key
      remoteRef:
        key: SearXNG
        property: secret_key
    - secretKey: open_metrics_token
      remoteRef:
        key: SearXNG
        property: open_metrics_token
    - secretKey: open_metrics_username
      remoteRef:
        key: SearXNG
        property: open_metrics_username
