---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
spec:
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: ${APP}-postgres-lb
              annotations:
                metallb.io/loadBalancerIPs: 10.0.10.251
                external-dns.alpha.kubernetes.io/hostname: davinci-pg.home.mirceanton.com
            spec:
              type: LoadBalancer
