---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: konflate-secret
    creationPolicy: Owner

  data:
    - secretKey: KONFLATE_APP_PRIVATE_KEY
      remoteRef:
        key: Renovate Operator - GitHub App PEM
        property: key
    - secretKey: KONFLATE_PUSH_TOKEN
      remoteRef:
        key: Konflate - Push Token
        property: password
