---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-auth
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: mosquitto-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        passwd: |
          {{ .z2m_hash }}
          {{ .homeassistant_hash }}
          {{ .touchkio_mirkdesk_hash }}
          {{ .touchkio_livingroom_hash }}

  data:
    - secretKey: z2m_hash
      remoteRef:
        key: "Mosquitto - z2m"
        property: hash
    - secretKey: homeassistant_hash
      remoteRef:
        key: "Mosquitto - homeassistant"
        property: hash
    - secretKey: touchkio_mirkdesk_hash
      remoteRef:
        key: "Mosquitto - touchkio-mirkdesk-pi"
        property: hash
    - secretKey: touchkio_livingroom_hash
      remoteRef:
        key: "Mosquitto - touchkio-livingroom-pi"
        property: hash
