---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firefly-keys
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: APP_KEY
      remoteRef:
        key: Firefly Keys
        property: APP_KEY

    - secretKey: STATIC_CRON_TOKEN
      remoteRef:
        key: Firefly Keys
        property: STATIC_CRON_TOKEN
---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &dataImporterName firefly-data-importer-token
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *dataImporterName
    creationPolicy: Owner

  data:
    - secretKey: FIREFLY_III_ACCESS_TOKEN
      remoteRef:
        key: Firefly Data Importer
        property: FIREFLY_III_ACCESS_TOKEN

    - secretKey: LUNCH_FLOW_API_KEY
      remoteRef:
        key: Firefly Data Importer
        property: LUNCH_FLOW_API_KEY
