---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: searxng

  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/searxng/searxng
              tag: 2026.4.24-a7ac696b4@sha256:c9100c29c14a77d5289263a671580226c3b8a396a1a0130d2f500f57076a0119
            env:
              SEARXNG_BASE_URL: https://search.home.mirceanton.com
              SEARXNG_PORT: &port 8080
              SEARXNG_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: searxng-secret
                    key: secret_key

            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
                add: [CHOWN, SETGID, SETUID, DAC_OVERRIDE]

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: searxng
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: searxng
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
            basicAuth:
              username:
                name: searxng-secret
                key: open_metrics_username
              password:
                name: searxng-secret
                key: open_metrics_token

    route:
      home:
        hostnames: ["search.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system

    persistence:
      config:
        type: configMap
        name: searxng-configmap
        globalMounts:
          - path: /etc/searxng/settings.yml
            subPath: settings.yml
            readOnly: true
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
