---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: crd-schema-publisher
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          serviceAccountName: crd-schema-publisher
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            seccompProfile:
              type: RuntimeDefault

          containers:
            - name: crd-schema-publisher
              image: ghcr.io/sholdee/crd-schema-publisher:latest
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: crd-schema-publisher
                      key: CLOUDFLARE_API_TOKEN
                - name: CLOUDFLARE_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: crd-schema-publisher
                      key: CLOUDFLARE_ACCOUNT_ID
                - name: CF_PAGES_PROJECT
                  value: k8s-schemas
                - name: OUTPUT_DIR
                  value: /output

              resources:
                requests:
                  cpu: 50m
                  memory: 1Gi
                limits:
                  cpu: 500m
                  memory: 1Gi

              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: [ALL]}
              volumeMounts:
                - name: output
                  mountPath: /output

          volumes:
            - name: output
              emptyDir: {}
