---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crd-schema-publisher
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: crd-schema-publisher
    creationPolicy: Owner

  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CRD Schemas - Cloudflare Token
        property: api_token
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: CRD Schemas - Cloudflare Token
        property: account_id
