apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
stringData:
    cf_email: ENC[AES256_GCM,data:RMQIvSo7SQBZSzJQklVfDX7M+TzSW6c=,iv:Orza3qLZVDXTj2TlOhcEF4LBY/GYqanbA35n7JZRHR4=,tag:WoktNIJHUHqUAjBE9Ci2eA==,type:str]
    cf_api_key: ENC[AES256_GCM,data:zFNHktMRLN2wEbpIqsiLY/T/0vwal1PagjtIMP6n335fw6XO7A==,iv:iiPLAKGAxaPt5cUfjpdI/hg5fp1XYi5VvxHVhqsiOyA=,tag:TtGBirEqaYSpFupk1hsyog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEp3UmY4b2lRcURtbW9N
            bXp6MjZxNmF0WjV6VkpkTlJ1YWdnaml5WHpRCjZZanMwbi9VUjlJSGczNDRjL1Qx
            SVk3VWQyRXFuZ3gvdW1xS1hMMmw0OXMKLS0tIDkrdDRCUVNLY0MxTGE1bDhselNm
            VHdpeHdzYzJWWlhWcmdSUDlQZVd5aGMKugxldUOC+mBWbud7O+A7+9LPHOp9xIgL
            0Tn876qMOSvwqwNpOVpzio1bChdzVhslLCe2PHl6ifgvjaWqfts4WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:57Z"
    mac: ENC[AES256_GCM,data:bKw/DVnyAof4JdN/227fZgVjV0nVOIh3taK0pQ1xG1E+YuUuSt0eym/o+dbBT3zP+IOWBiyf9wHnJNOynOtwJoLDcv1UeKbQp54wY8aYZFR9+e1GWGVZkWj6bamhz2YTJDAQeaREhAj1NOwOQZNa90UJ5Rv4g75wrBOSzYxHqug=,iv:ZaArIQyLRXrN3NpFBerDtHb6X3JYJLtR32LS5Qs6xdE=,tag:eZMbpc1+VnruHPtfE8lgZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
