apiVersion: v1
kind: Secret
metadata:
    name: terraform-cloud-token
stringData:
    token: ENC[AES256_GCM,data:Bok2tF+smZ4DVNzbAmYJRk+3o/m+mDCvu2IVowbYOR3MXUjALrDyvISSO8LeplnNu6/+h2YcQsEAAefy6nb4Gj3my1YYCjbOC+9anLhVGZaWOtaa//O+UOd+,iv:d7WSAffqT8QeFSxi6mB0qzfw1fVzZUn69VTgkdUpuX4=,tag:0HZKEHIuOEwLuKNNU2bc/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTG5IWkJiMjFNSDlRUWw3
            RkZIbnVXZ0xEb2NTYzNjRS85ZGdKcUZXZTE0CnZBWW1VS1ozY3FtVzR4YUJqakpn
            dGF4YmJLSDRhWTFTQ1pXM2VKbER2MncKLS0tIEx1Yk83dHhqUERQSVhoWU1abDFD
            T095UUV3U1JObDVmNEhuZXRSUTgwWTAKHvfBCh72jl5yXQPZ63dwqvbM7Q6684D9
            ElMd7zvupF5t6Dg1G7vtVwA9fN/HZ1Keao624mOhU1MRf7gN2VF/zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T18:28:57Z"
    mac: ENC[AES256_GCM,data:fkpTjUovHRyH13Cr4iybqcUfcnLhmR3OtToFu0MEXlfbKtflL+ujgtqQvghSiPYrroUdnSNfB4GsL9KqNZYMp94Rt651SfBFtjYc7+p2T2jay/GrzlKE1DXaoZQi+r0NLMTW8H3pbSOf8nVY6Sauj4icZJyowMIQf9Lr9e3syTE=,iv:EEpZjoVuA0hBw5xl6K3wzSAr3PIYZfxWffG0Y1KeZ54=,tag:3N0+R2PzqDHEfcq+bAFNHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
