---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-secret.yaml
  - ./grafana-dashboard.yaml
  - ./helm-release.yaml
  - ./oci-repository.yaml
  - ./scrape-config.yaml

configMapGenerator:
  - name: telegraf-config
    files:
      - telegraf.conf=./files/telegraf.conf
  - name: zigbee-smart-plugs-dashboard
    files:
      - dashboard.json

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
