---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name karakeep-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: "Karakeep - Keys"
        property: nextauth_secret
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: "Karakeep - Keys"
        property: meilisearch_master_key
    - secretKey: PROMETHEUS_AUTH_TOKEN
      remoteRef:
        key: "Karakeep - Keys"
        property: prometheus_auth_token
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: "Karakeep - Keycloak"
        property: keycloak_client_secret
