---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-mcp
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grafana-mcp

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      grafana-mcp:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: grafana/mcp-grafana
              tag: 0.17.0
            env:
              GRAFANA_URL: http://grafana-service:3000
              GRAFANA_ORG_ID: "1"
              #! TODO: this has been manually created for now, but I should automate it and store it in the repo as well
              #! maybe look for a terraform provider for Grafana and manage it that way?
              GRAFANA_AUTH:
                valueFrom:
                  secretKeyRef:
                    name: grafana-mcp-secret
                    key: GRAFANA_AUTH

            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: {type: RuntimeDefault}

    service:
      app:
        controller: grafana-mcp
        ports:
          http:
            port: *port

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
