---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: mcp
spec:
  instanceName: grafana
  role: Editor
  tokens:
    - name: mcp-token
      secretName: grafana-mcp-token
