---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name z2m-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_USER
      remoteRef:
        key: "Mosquitto - z2m"
        property: username
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: "Mosquitto - z2m"
        property: password

    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY
      remoteRef:
        key: "Zigbee2MQTT"
        property: NETWORK_KEY
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID
      remoteRef:
        key: "Zigbee2MQTT"
        property: PAN_ID
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
      remoteRef:
        key: "Zigbee2MQTT"
        property: CHANNEL
    - secretKey: ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID
      remoteRef:
        key: "Zigbee2MQTT"
        property: EXT_PAN_ID
