---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: zigbee2mqtt

  values:
    controllers:
      zigbee:
        annotations: {reloader.stakater.com/auto: "true"}

        containers:
          z2m:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.9.1@sha256:574b2bd0dcbb59fae6edbbb81a35b5563291d3825da0225f0078aa5575dac37f
            envFrom:
              - secretRef: {name: z2m-secret}
              - configMapRef: {name: z2m-config}
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

            probes:
              liveness: {enabled: true}
              readiness: {enabled: true}
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http: {port: 80}
          onboard: {port: 8080}

    route:
      home:
        hostnames: ["z2m.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system
      tailscale:
        hostnames: ["z2m.ts.mirceanton.com"]
        parentRefs:
          - name: envoy-tailscale
            namespace: network-system

    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /config
