---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: zigbee-dongle
spec:
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  advanced:
    restoreToOriginalReplicaCount: true
 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee2mqtt

  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring-system.svc.cluster.local:9090
        query: max_over_time(probe_success{instance=~"sonoff-dongle-max.+"}[1m])
        threshold: "1"
        ignoreNullValues: "0"
