---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: z2m-mqtt-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: z2m-mqtt-secret
    creationPolicy: Owner

  data:
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_USER
      remoteRef:
        key: "Mosquitto - z2m"
        property: username
    - secretKey: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
      remoteRef:
        key: "Mosquitto - z2m"
        property: password
