# Base config
sunshine_name = selkies-gaming
origin_web_ui_allowed = lan

file_apps = /etc/sunshine/apps.json

# Optional environment-driven settings
csrf_allowed_origins = https://10.0.10.15

# min_log_level = debug
min_log_level = info
# min_log_level = warning
# min_log_level = error

# capture = nvfbc
capture = x11
# capture = kms

# 1 = fastest, 7 = highest quality.
nvenc_preset = 2

# nvenc_twopass = disabled
# nvenc_twopass = quarter_res
nvenc_twopass = disabled

nvenc_spatial_aq = enabled
# nvenc_spatial_aq = disabled

# Lower latency at the expense of compression efficiency
fec_percentage = 20

# Enable QoS tagging on supported networks
upnp = enabled
