---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./oci-repository.yaml
  - ./helm-release.yaml
  - ./external-secret.yaml
  - ./grafana-dashboard.yaml

configMapGenerator:
  - name: jellyfin-dashboard
    options:
      disableNameSuffixHash: true
    files:
      - dashboard.json
