---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: llmkube
spec:
  interval: 1h
  url: oci://ghcr.io/mirceanton/forks/llmkube/chart/llmkube
  ref:
    tag: "0.7.8"

  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
