---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    scheduler.alpha.kubernetes.io/node-selector: k8s.mirceanton.com/remote-node=true
