---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sure-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: Sure - Keys
        property: secret_key

    - secretKey: TWELVE_DATA_API_KEY
      remoteRef:
        key: Sure - Keys
        property: twelve_data_api_key

    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: Sure - Keycloak
        property: keycloak_client_secret

    - secretKey: OPENAI_ACCESS_TOKEN
      remoteRef:
        key: Sure - LiteLLM
        property: password

    - secretKey: BRAND_FETCH_CLIENT_ID
      remoteRef:
        key: Sure - Keys
        property: brandfetch_api_key

    - secretKey: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
      remoteRef:
        key: Sure - Keys
        property: active_record_encryption_primary_key

    - secretKey: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
      remoteRef:
        key: Sure - Keys
        property: active_record_encryption_deterministic_key

    - secretKey: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
      remoteRef:
        key: Sure - Keys
        property: active_record_encryption_key_derivation_salt
