---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: hermes-config-template
            items:
              - key: config.yaml
        - configMap:
            name: hermes-config-template
            items:
              - key: env

  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: Hermes
        property: litellm_key

    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: Discord App - Mr. Borboto
        property: token

    - secretKey: DISCORD_ALLOWED_USERS
      remoteRef:
        key: Hermes
        property: mirceanton_user_id

    - secretKey: DISCORD_HOME_CHANNEL
      remoteRef:
        key: Hermes
        property: discord_home_channel_id

    - secretKey: DISCORD_ALERTMANAGER_CHANNEL
      remoteRef:
        key: Hermes
        property: discord_alertmanager_channel_id
