---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/keycloak.hostzero.com/keycloakclient_v1beta1.json
apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakClient
metadata:
  name: "${APP}"
spec:
  clusterRealmRef:
    name: homelab

  clientId: "${APP}"
  protocol: openid-connect

  definition:
    clientId: "${APP}"
    name: "${APP}"
    protocol: openid-connect
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    redirectUris:
      - "https://${APP}.home.mirceanton.com/*"
    webOrigins:
      - "https://${APP}.home.mirceanton.com"

  # Auto-create Secret with client credentials
  clientSecretRef:
    name: "${APP}-oidc-secret"
    create: true
    clientIdKey: client-id
    clientSecretKey: client-secret
