---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie

  bootstrap:
    initdb:
      database: litellm
      owner: litellm

  storage:
    storageClass: openebs-zfs
    size: 4Gi

  walStorage:
    storageClass: openebs-zfs
    size: 2Gi

  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 256Mi

  postgresql:
    pg_hba:
      - host all all 10.244.0.0/16 scram-sha-256
