---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: litellm-secret
    creationPolicy: Owner

  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LiteLLM
        property: password

    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: LiteLLM
        property: salt_key
