---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: master-key
      remoteRef:
        key: LiteLLM
        property: LITELLM_MASTER_KEY

    - secretKey: salt-key
      remoteRef:
        key: LiteLLM
        property: LITELLM_SALT_KEY

    - secretKey: firefly-mcp-token
      remoteRef:
        key: "Firefly MCP"
        property: token
