---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: mr-borboto-auth-token
spec:
  appID: "900136"
  installID: "53131225"
  auth:
    privateKey:
      secretRef:
        name: mr-borboto-pem
        key: private_key_pem

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm-github-mcp-token
spec:
  refreshInterval: 55m
  target:
    name: *name
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_MCP_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: mr-borboto-auth-token
