---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-secret.yaml
  - ./github-access-token.yaml
  - ./grafana-dashboard.yaml
  - ./litellm-chatgpt-tokens.pvc.yaml
  - ./litellm-proxy.yaml

configMapGenerator:
  - name: litellm-dashboard
    options:
      disableNameSuffixHash: true
    files:
      - dashboard.json
