---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-secret.yaml
  - ./github-mcp-token.yaml
  - ./grafana-dashboard.yaml
  - ./helm-release.yaml
  - ./oci-repository.yaml

configMapGenerator:
  - name: litellm-config
    options:
      disableNameSuffixHash: true
    files:
      - config.yaml=./files/config.yaml
  - name: litellm-dashboard
    options:
      disableNameSuffixHash: true
    files:
      - dashboard.json
