---
model_list:
  # -------------------------------- QWEN EMBEDDING --------------------------------
  - model_name: qwen3-embedding-0.6b
    litellm_params:
      model: openai/qwen3-embedding-0.6b
      api_base: http://qwen3-embedding-0-6b.ai.svc.cluster.local:8080/v1
      api_key: "N/A"
    model_info:
      mode: embedding

  - model_name: qwen3.8-27B-2bit
    litellm_params:
      model: openai/qwen3.8-27B
      api_base: http://qwen3-8-27b:8080/v1
      api_key: "N/A"

  # -------------------------------- QWEN IMAGE --------------------------------
  - model_name: qwen-image-3.0-pro
    litellm_params:
      model: qwencloud/qwen-image-3.0-pro
      api_base: &qwenURL https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1
      api_key: os.environ/QWEN_KEY

  - model_name: qwen-image-3.0
    litellm_params:
      model: qwencloud/qwen-image-3.0
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

  # ----------------------------------- QWEN 3.8 -----------------------------------
  - model_name: qwen3.8-max
    litellm_params:
      model: qwencloud/qwen3.8-max
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

  - model_name: qwen3.8-flash
    litellm_params:
      model: qwencloud/qwen3.8-flash
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

  # ----------------------------------- QWEN 3.7 -----------------------------------
  - model_name: qwen3.7-plus
    litellm_params:
      model: qwencloud/qwen3.7-plus
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

  # ----------------------------------- GLM -----------------------------------
  - model_name: glm-5.2
    litellm_params:
      model: qwencloud/glm-5.2
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

  # ---------------------------------- DEEPSEEK ----------------------------------
  - model_name: deepseek-v4-pro
    litellm_params:
      model: qwencloud/deepseek-v4-pro
      api_base: *qwenURL
      api_key: os.environ/QWEN_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  prometheus_adapter: true
  require_auth_for_metrics_endpoint: false

  drop_params: true
  request_timeout: 600
  num_retries: 2
  retry_after: 5
  set_verbose: false
