---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ./namespace.yaml
  - ./cilium
  - ./generic-device-plugin
  - ./keda
  - ./metrics-server
  - ./nvidia
  - ./reloader
