---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-mcp-secret
spec:
  refreshInterval: 55m

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: mr-borboto-auth-token
