---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-operator
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - honorLabels: true
      port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
