---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-exporter-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: jellyfin-exporter-secret
    creationPolicy: Owner

  data:
    - secretKey: JELLYFIN_TOKEN
      remoteRef:
        key: Jellyfin Exporter - API Key
        property: password
