---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-exporter
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: jellyfin-exporter

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true

    controllers:
      jellyfin-exporter:
        type: statefulset

        containers:
          jellyfin-exporter:
            image:
              repository: rebelcore/jellyfin-exporter
              tag: v1.5.2@sha256:8a1294b7fea80993e4ec18220e391578e0f9ca9e109294fd6a379d2cb5213c85

            env:
              JELLYFIN_ADDRESS: http://jellyfin:8096
              JELLYFIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: jellyfin-exporter-secret
                    key: JELLYFIN_TOKEN

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 32Mi

            # TODO: add probes?
            probes:
              liveness: { enabled: false }
              readiness: { enabled: false }
              startup: { enabled: false }

            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

    service:
      jellyfin-exporter:
        controller: jellyfin-exporter
        ports:
          http: { port: 9594 }

    serviceMonitor:
      jellyfin-exporter:
        serviceName: jellyfin-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 15s
            scrapeTimeout: 5s
