---
title: "Home Dashboard"
subtitle: ""
header: false
footer: false
columns: 5
connectivityCheck: true

links:
  - name: "Home"
    icon: "fas fa-home"
    url: "/"

  - name: "Bomkii"
    icon: "fas fa-boxes-stacked"
    url: "#bomkii"

  - name: "mirceanton"
    icon: "fas fa-user"
    url: "#mirceanton"

  - name: "Admin"
    icon: "fas fa-server"
    url: "#admin"

services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Jellyfin"
        subtitle: "Media Server"
        url: "https://movies.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/jellyfin.webp"

      - name: "Immich"
        subtitle: "Photo Library"
        url: "https://photos.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/immich.webp"

      - name: "Feishin"
        subtitle: "Music Player"
        url: "https://music.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/feishin.webp"

      - name: "Navidrome"
        subtitle: "Music Server"
        url: "https://navidrome.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/navidrome.webp"

      - name: "Paperless"
        subtitle: "Document Management"
        url: "https://documents.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/paperless-ng.webp"

      - name: "BookOrbit"
        subtitle: "Book Library"
        url: "https://bookorbit.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/booklore.webp"

      - name: "Karakeep"
        subtitle: "Bookmark Manager"
        url: "https://karakeep.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/karakeep.webp"

  - name: "Home"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        subtitle: "Home Automation"
        url: "https://homeassistant.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/home-assistant.webp"

      - name: "SparkyFitness"
        subtitle: "Fitness Tracker"
        url: "https://fitness.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/sparky-fitness.webp"

      - name: "Sure"
        subtitle: "Financial Manager"
        url: "https://finance.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/sure.webp"

      - name: "Vikunja"
        subtitle: "Task Manager"
        url: "https://tasks.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/vikunja.webp"

  - name: "Maker"
    icon: "fas fa-cube"
    items:
      - name: "Bambuddy"
        subtitle: "3D Printer Manager"
        url: "https://bambuddy.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/bambu-lab.webp"

      - name: "Manyfold"
        subtitle: "3D Model Library"
        url: "https://manyfold.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/manyfold.webp"

  - name: "Downloads"
    icon: "fa-solid fa-skull-crossbones"
    items:
      - name: "Qui"
        subtitle: "Torrent Client"
        url: "https://torrent.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/qui.webp"

      - name: "Sonarr"
        subtitle: "TV Shows"
        url: "https://sonarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/sonarr.webp"

      - name: "Radarr"
        subtitle: "Movies"
        url: "https://radarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/radarr.webp"

      - name: "Lidarr"
        subtitle: "Music"
        url: "https://lidarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/lidarr.webp"

      - name: "Shelfmarrk"
        subtitle: "Books"
        url: "https://shelfmark.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/shelfmark.webp"

      - name: "Bazarr"
        subtitle: "Subtitles"
        url: "https://bazarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/bazarr.webp"

      - name: "Streamarr"
        subtitle: "Audio & Subtitle Janitor"
        url: "https://streamarr.home.mirceanton.com"
        target: "_blank"
        icon: "fas fa-sliders"

      - name: "Prowlarr"
        subtitle: "Indexer Manager"
        url: "https://prowlarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/prowlarr.webp"

  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: ConvertX
        subtitle: "File Converter"
        url: "https://convert.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/convertx.webp"

      - name: "Omni-Tools"
        subtitle: "Various Utilities"
        url: "https://tools.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/omni-tools.webp"

      - name: "OpenSpeedTest"
        subtitle: "Network Speed Test"
        url: "https://speedtest.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/openspeedtest.webp"

      - name: "Carbon"
        subtitle: "Code Screenshot Tool"
        url: "https://carbon.home.mirceanton.com"
        target: "_blank"
        icon: "fas fa-code"

      - name: "Draw.io"
        subtitle: "Diagram Editor"
        url: "https://diagrams.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/draw-io.webp"

      - name: "SearXNG"
        subtitle: "Meta Search Engine"
        url: "https://search.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/searxng.webp"
