---
title: "Home Dashboard"
subtitle: ""
header: false
footer: false
columns: 5
connectivityCheck: true

links: []

services:
  - name: "Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Jellyfin"
        subtitle: "Media Server"
        url: "https://movies.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/jellyfin.webp"

      - name: "Immich"
        subtitle: "Photo Library"
        url: "https://photos.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/immich.webp"

      - name: "Feishin"
        subtitle: "Music Player"
        url: "https://music.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/feishin.webp"

      - name: "Navidrome"
        subtitle: "Music Server"
        url: "https://navidrome.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/navidrome.webp"

      - name: "Booklore"
        subtitle: "Book Library"
        url: "https://books.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/booklore.webp"

      - name: "Karakeep"
        subtitle: "Bookmark Manager"
        url: "https://karakeep.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/karakeep.webp"

  - name: "Home Automation"
    icon: "fas fa-home"
    items:
      - name: "Home Assistant"
        subtitle: "Home Automation"
        url: "https://homeassistant.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/home-assistant.webp"

      - name: "Zigbee2MQTT"
        subtitle: "Zigbee Bridge"
        url: "https://z2m.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/zigbee2mqtt.webp"

  - name: "Finances"
    icon: "fas fa-wallet"
    items:
      - name: "Firefly"
        subtitle: "Financial Manager"
        url: "https://firefly.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/firefly-iii.webp"

      - name: "Firefly Data Importer"
        subtitle: "Data Importer"
        url: "https://firefly-importer.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/firefly-iii.webp"

  - name: "Miscellaneous"
    icon: "fas fa-code"
    items:
      - name: "Omni-Tools"
        subtitle: "Various Utilities"
        url: "https://tools.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/omni-tools.webp"

  - name: "Downloads"
    icon: "fa-solid fa-skull-crossbones"
    items:
      - name: "Qui"
        subtitle: "Torrent Client"
        url: "https://torrent.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/qui.webp"

      - name: "Sonarr"
        subtitle: "TV Shows Management"
        url: "https://sonarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/sonarr.webp"

      - name: "Radarr"
        subtitle: "Movie Management"
        url: "https://radarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/radarr.webp"

      - name: "Lidarr"
        subtitle: "Music Management"
        url: "https://lidarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/lidarr.webp"

      - name: "Shelfmark"
        subtitle: "Bookmarks Manager"
        url: "https://shelfmark.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/shelfmark.webp"

      - name: "Bazarr"
        subtitle: "Subtitle Management"
        url: "https://bazarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/bazarr.webp"

      - name: "Tdarr"
        subtitle: "Media Transcoder"
        url: "https://tdarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/tdarr.webp"

      - name: "Prowlarr"
        subtitle: "Indexer Manager"
        url: "https://prowlarr.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/prowlarr.webp"

  - name: "YouTube"
    icon: "fab fa-youtube"
    items:
      - name: "Penpot"
        subtitle: "Design Tool"
        url: "https://penpot.home.mirceanton.com"
        target: "_blank"
        logo: "assets/icons/webp/penpot.webp"

      - name: "Teleprompter"
        subtitle: ""
        url: "https://teleprompter.home.mirceanton.com"
        target: "_blank"
        icon: "fas fa-scroll"
