---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: blog

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      blog:
        containers:
          app:
            image:
              repository: ghcr.io/mirceanton/mirceanton.com
              tag: latest

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  failureThreshold: 5
                  periodSeconds: 5

            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: blog
        ports:
          http:
            port: 8080
            targetPort: 8080

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
