---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./budget-board
  - ./carbon
  - ./convertx
  - ./drawio
  - ./firefly
  - ./homer
  - ./omni-tools
  - ./openspeedtest
  - ./searxng
  - ./sparkyfitness
  - ./sure
  - ./vikunja
