---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "${APP}-dragonfly"
spec:
  podMetricsEndpoints:
    - port: admin
      path: /metrics
      honorLabels: true
      interval: 15s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
