---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: services-pool
spec:
  blocks:
    - cidr: 10.0.10.250/32 # envoy-services
    - cidr: 10.0.10.251/32 # davinci-postgres
    - cidr: 10.0.10.252/32 # mosquitto
    - cidr: 10.0.10.253/32 # minecraft-router

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: admin-pool
spec:
  blocks:
    - cidr: 10.0.0.250/32 # envoy-admin
