---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: llama-server
spec:
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 1800
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: llama-server

  advanced:
    restoreToOriginalReplicaCount: true

  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://discord-bot-autoscaler.tools.svc.cluster.local:8080/metrics/llama-server"
        valueLocation: "value"

    - type: cpu
      metricType: Utilization
      metadata:
        value: "5"
