apiVersion: v1
kind: Secret
metadata:
    name: minio-connection-details
stringData:
    minio_user: ENC[AES256_GCM,data:X+WpW7S01bSY0Z12YFMlysPDtA==,iv:RPrH1sfVycuhEP1W9jRWeC0imp9aASvsyfc/rmfrxic=,tag:TyZAW2GR1scvjBFEwX1clw==,type:str]
    minio_pass: ENC[AES256_GCM,data:sHn5I4QKysqUVSVjTICGFkEUhA==,iv:GXOYJdir2CIV8PfRztDrvqnwjAsyOY6JX1iB2U0RAlU=,tag:DhIa+YlnU4NlWFca/wlTqQ==,type:str]
    minio_server: ENC[AES256_GCM,data:ool3eC2oLy4dBne4djGbOoECv5pcvh5oKuA=,iv:ie7PCzoJ1M/9IyFZmco9VZrYm7X296hhNeow4v8RLbo=,tag:MbLiOmAfblpuPsLswQqDhA==,type:str]
    minio_ssl: ENC[AES256_GCM,data:laIMXA==,iv:2tMgE4hRGeuXFqe8QPHsxTiNxVXerRKZuJa/MEjX7NY=,tag:TmV5eQtVhUHlGqGqrPfFRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ghlphrjhpdlt83clr4y33efd3cu7v2ysl88fhq7c6hw2xpnl5gpq9jq2mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWk1XVGVxL1pwVDh6QkNm
            V3pIMG90NTYva1ZZWXFLd0E1cDViNnp0OFdVCmF0SnRYT25QT1htNGNOSHpUVTRu
            WUk2cHhxSVcvQTZDRWpDbUU2SUVRd2cKLS0tIGJsdSt2YWR6bGR2WXZpMU9XMU9q
            Ukg2WWtGL2NQVjFKK2svVVo3WnE1ODgKl7RhxyHbzTj5PETELc4xW42BrP11rMoZ
            rY54P2yqQBu5RIRZjjI3uniR956SuhMFRa386sw/KkNuwLwU0PHtDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T19:25:58Z"
    mac: ENC[AES256_GCM,data:Jz8OsXYAl0kyUT0oNrkUHiD9TPK6XPQG9ChL8Fuyui9KQftyD7h9/DaD/yMBLcOBc+Bgr3nywfFSCkgx1z4av/ZzefjU3ldL65Vkd3GpHbvOnH3n0raHVbI+QxjjLDVaxJpvrxR9kS4oF4MQd+8ZMWAfIB18cwlyV0GDqfRDsjY=,iv:SJcMFnRrMaCeTRx4FQQ1+PZPyV7ps+4BXBs13LGymwI=,tag:l7H3zlUMBTvcj1i55l6kEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
