---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name youtube-exporter-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: *name
    creationPolicy: Owner

  data:
    - secretKey: CHANNEL_ID
      remoteRef:
        key: YouTube Data API
        property: username
    - secretKey: API_KEY
      remoteRef:
        key: YouTube Data API
        property: password
