---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: downloads

resources:
  - ./namespace.yaml
  - ./grafana-folder.yaml
  - ./arr-dashboard
  - ./arr-hub
  - ./bazarr
  - ./flaresolverr
  - ./lidarr
  - ./prowlarr
  - ./qbittorrent
  - ./qui
  - ./radarr
  - ./shelfmark
  - ./sonarr
  - ./streamarr
