---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: librechat-secret
    creationPolicy: Owner

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: LibreChat
        property: jwt_secret

    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: LibreChat
        property: jwt_refresh_secret

    - secretKey: CREDS_KEY
      remoteRef:
        key: LibreChat
        property: creds_key

    - secretKey: CREDS_IV
      remoteRef:
        key: LibreChat
        property: creds_iv

    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LiteLLM
        property: master_key
