---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: librechat-mongodb
spec:
  interval: 15m
  url: oci://registry-1.docker.io/cloudpirates/mongodb
  ref:
    tag: 0.17.6

  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
