---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minio
  namespace: flux-system
  labels:
    patching.home.mirceanton.com/source-ref: true
    patching.home.mirceanton.com/intervals: true
    patching.home.mirceanton.com/post-build: true
    patching.home.mirceanton.com/decryption: true
spec:
  path: kubernetes/infra-cluster/apps/minio/minio/app
  targetNamespace: minio
  prune: true
  dependsOn: []
