---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-sunshine-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-zfs-cache
