---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rreading-glasses-hardcover
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: rreading-glasses-hardcover
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HARDCOVER_AUTH: "Bearer {{ .token }}"

  data:
    - secretKey: token
      remoteRef:
        key: Hardcover API Key
        property: password
