---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./qwencloud-token.external-secret.yaml

  # Models
  - ./deepseek.yaml
  - ./glm.yaml
  - ./qwen-audio-tts.yaml
  - ./qwen-image-3.0.yaml
  - ./qwen3.7.yaml
  - ./qwen3.8.yaml
  - ./wan-2.7.yaml
