---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ai
  - ./database-system
  - ./default
  - ./demo-b
  - ./development
  - ./downloads
  - ./finances
  - ./fitness
  - ./flux-system
  - ./games
  - ./github-actions
  - ./home-automation
  - ./kube-system
  - ./media
  - ./monitoring-system
  - ./network-system
  - ./security-system
  - ./storage-system
  - ./tools
  - ./youtube
