---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: arr-hub-session-secret
spec:
  length: 64
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name arr-hub-session-secret
spec:
  refreshInterval: "0"

  target:
    name: *name
    creationPolicy: Owner

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: arr-hub-session-secret
