---
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: gemma-4-26b-a4b
spec:
  source: https://huggingface.co/unsloth/gemma-4-26B-A4B-it-GGUF/resolve/main/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf
  format: gguf
  quantization: UD-Q4_K_M
  hardware:
    accelerator: vulkan
    gpu:
      enabled: true
      count: 1
      vendor: amd
      runtime: vulkan
      layers: -1
      resourceName: devic.es/dri-render

---
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: gemma-4-26b-a4b
  labels:
    krr/ignore: "true"
spec:
  modelRef: gemma-4-26b-a4b
  image: ghcr.io/ggml-org/llama.cpp:server-vulkan
  replicas: 1
  priority: batch
  parallelSlots: 1 # single concurrent session

  flashAttention: true
  contextSize: 131072
  uBatchSize: 1024
  cacheTypeK: q8_0
  cacheTypeV: q8_0

  resources:
    cpu: 500m # just for scheduling purposes...
    memory: 1Gi # just for scheduling purposes...
    gpu: 1
    gpuMemory: 24Gi

  endpoint:
    port: 8080
    type: ClusterIP
