---
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: gemma-4-12b
spec:
  source: https://huggingface.co/unsloth/gemma-4-12B-it-qat-GGUF/resolve/main/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
  format: gguf
  quantization: UD-Q4_K_XL
  hardware:
    accelerator: cuda
    gpu:
      enabled: true
      count: 1
      vendor: nvidia
      layers: -1

---
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: gemma-4-12b
  labels:
    krr/ignore: "true"
spec:
  modelRef: gemma-4-12b
  image: ghcr.io/ggml-org/llama.cpp:server-cuda
  runtimeClassName: nvidia
  replicas: 1
  priority: batch
  parallelSlots: 1 # single concurrent session

  flashAttention: true
  contextSize: 16384
  uBatchSize: 512
  cacheTypeK: q8_0
  cacheTypeV: q8_0

  resources:
    cpu: 500m # just for scheduling purposes...
    memory: 1Gi # just for scheduling purposes...
    gpu: 1
    gpuMemory: 8Gi

  endpoint:
    port: 8080
    type: ClusterIP
