---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./servicemonitor.yaml
  - ./qwen-35b.yaml
  - ./gemma-4-26B-A4B.yaml
  - ./qwen3-0.6b.yaml
  - ./qwen3-embedding-0.6b.yaml
