---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: immich-secret
    creationPolicy: Owner

  data:
    - secretKey: IMMICH_OAUTH_CLIENT_SECRET
      remoteRef:
        key: Immich - Keycloak
        property: keycloak_client_secret
