---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: sparkyfitness-secret
    creationPolicy: Owner

  data:
    - secretKey: SPARKY_FITNESS_API_ENCRYPTION_KEY
      remoteRef:
        key: SparkyFitness
        property: api_encryption_key
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: SparkyFitness
        property: better_auth_secret
