---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./qwen-image-3.0-pro.yaml
  - ./qwen-image-3.0.yaml
  - ./qwen3.8-max.yaml
  - ./qwen3.8-flash.yaml
  - ./qwen3.7-plus.yaml
  - ./glm-5.2.yaml
  - ./deepseek-v4-pro.yaml