---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: qwen3.7-plus
spec:
  modelName: qwen3.7-plus
  params:
    model: qwencloud/qwen3.7-plus
    apiBase: https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1
    apiKeyRef:
      name: litellm-secret
      key: QWEN_KEY