---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APP}-postgres-backup
spec:
  schedule: "0 */2 * * *" # every 2 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568

          containers:
            - name: backup
              image: ${CNPG_IMAGE:-ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie}
              command: ["/bin/bash", "/scripts/backup.sh"]
              env:
                - name: APP_NAME
                  value: ${APP}
                - name: BACKUP_DIR
                  value: /backup/${APP}
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-postgres-app
                      key: host
                - name: PGPORT
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-postgres-app
                      key: port
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-postgres-app
                      key: username
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-postgres-app
                      key: dbname
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-postgres-app
                      key: password

              volumeMounts:
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
                - name: backup
                  mountPath: /backup

              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}

          volumes:
            - name: scripts
              configMap:
                name: ${APP}-postgres-scripts
                defaultMode: 0755
            - name: backup
              nfs:
                server: nas.stor.h.mirceanton.com
                path: /mnt/tank/Backups/HomeOps
