# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mr-borboto-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  data:
  - secretKey: private_key_pem
    remoteRef:
      key: Renovate Operator - GitHub App PEM
      property: key

---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name docker-hub-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        DOCKERHUB_USERNAME: "{{ .username }}"
        DOCKERHUB_TOKEN: "{{ .password }}"
  dataFrom:
    - extract:
        key: Renovate Operator - DockerHub Token

