---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: mirceanton
spec:
  schedule: 15/30 * * * * # every 30 minutes
  image: ghcr.io/renovatebot/renovate:43.261.2
  parallelism: 5

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  discoveryFilters: ["mirceanton/*"]
  provider: { name: github }

  extraEnv:
    - name: RENOVATE_REDIS_URL
      value: "redis://renovate-dragonfly:6379"
    - name: RENOVATE_CACHE_DIR
      value: /tmp/renovate-cache
    - name: RENOVATE_REPOSITORY_CACHE
      value: enabled
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        ["pnpm run bundle", "mise install", "mise lock"]
    - name: RENOVATE_ALLOWED_UNSAFE_EXECUTIONS
      value: |-
        ["mise"]
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [
          {
            "hostType": "docker",
            "matchHost": "docker.io",
            "username": "$(DOCKERHUB_USERNAME)",
            "password": "$(DOCKERHUB_TOKEN)"
          }
        ]

  extraVolumes:
    - name: renovate-cache
      persistentVolumeClaim:
        claimName: renovate-cache

  extraVolumeMounts:
    - name: renovate-cache
      mountPath: /tmp/renovate-cache

  secretRef: mr-borboto-auth-token
  webhook:
    enabled: true
    authentication:
      enabled: false
