---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: media

  path: ./apps/media/immich/app
  components:
    - ../../../../components/volsync/
    - ../../../../components/dragonfly/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 100Gi
      DRAGONFLY_CPU_REQUEST: 1000m
      DRAGONFLY_MEMORY_REQUEST: 2Gi
      DRAGONFLY_MEMORY_LIMIT: 2Gi
      DRAGONFLY_PROACTOR_THREADS: "4"

  dependsOn:
    - name: dragonfly-operator
      namespace: database-system
    - name: cloudnative-pg-operator
      namespace: database-system
