---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mcp-homeassistant
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  targetNamespace: ai

  path: ./apps/ai/mcp-homeassistant/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app

  dependsOn:
    - name: 1password-connect
      namespace: security-system
    - name: home-assistant
      namespace: home-automation
