---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bambuddy-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: bambuddy-secret
    creationPolicy: Owner

  data:
    - secretKey: HA_TOKEN
      remoteRef:
        key: Bambuddy
        property: HA_TOKEN
