---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: ${CNPG_REPLICAS:-1}
  imageName: ${CNPG_IMAGE:-ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie}

  bootstrap:
    initdb:
      database: ${APP}
      owner: ${APP}

  storage:
    storageClass: ${CNPG_DATA_STORAGE_CLASS:-openebs-zfs}
    size: ${CNPG_DATA_STORAGE_SIZE:-4Gi}

  walStorage:
    storageClass: ${CNPG_WAL_STORAGE_CLASS:-openebs-zfs}
    size: ${CNPG_WAL_STORAGE_SIZE:-2Gi}

  resources:
    requests:
      cpu: ${CNPG_CPU_REQUEST:-100m}
      memory: ${CNPG_MEMORY_REQUEST:-256Mi}
    limits:
      memory: ${CNPG_MEMORY_LIMIT:-512Mi}

  postgresql:
    pg_hba:
      - host all all ${CNPG_PG_HBA_CIDR:-10.244.0.0/16} scram-sha-256

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: "${APP}-postgres-backup"

  monitoring:
    enablePodMonitor: true
