---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-cnpg-backup"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: "${APP}-cnpg-backup-secret"
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        CNPG_BACKUP_ENDPOINT: "{{ .endpoint }}"
        CNPG_BACKUP_BUCKET: "{{ .bucket }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: &opSecretName Garage HomeOps Backups Key
        property: username
    - secretKey: secret_key
      remoteRef:
        key: *opSecretName
        property: password
    - secretKey: endpoint
      remoteRef:
        key: *opSecretName
        property: url
    - secretKey: bucket
      remoteRef:
        key: *opSecretName
        property: bucket
