---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-cnpg-backup"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword

  target:
    name: "${APP}-cnpg-backup"
    template:
      engineVersion: v2
      data:
        ACCESS_KEY_ID: "{{ .access_key }}"
        ACCESS_SECRET_KEY: "{{ .secret_key }}"
        ENDPOINT_URL: "{{ .endpoint }}"

  data:
    - secretKey: access_key
      remoteRef:
        key: &opSecretName Garage HomeOps Backups Key
        property: username
    - secretKey: secret_key
      remoteRef:
        key: *opSecretName
        property: password

    - secretKey: endpoint
      remoteRef:
        key: *opSecretName
        property: url
