---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${APP}-postgres
spec:
  schedule: "0 */2 * * *"
  backupOwnerReference: self
  cluster:
    name: ${APP}-postgres
  method: barmanObjectStore
  online: true
  onlineConfiguration:
    waitForArchive: true
