---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-homeassistant-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore

  target:
    name: mcp-homeassistant-secret
    creationPolicy: Owner

  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: Home Assistant MCP
        property: token
