---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sparkyfitness
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 15m
  targetNamespace: fitness

  path: ./apps/fitness/sparkyfitness/app
  components:
    - ../../../../components/volsync/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi

  dependsOn:
    - name: cloudnative-pg-operator
      namespace: database-system
    - name: openebs
      namespace: storage-system
    - name: external-secrets-operator
      namespace: security-system
    - name: volsync
      namespace: storage-system
