# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: flaresolverr

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      flaresolverr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.0
            env:
              PROMETHEUS_ENABLED: "true"
              PROMETHEUS_PORT: 8000
            resources:
              requests:
                cpu: 20m
                memory: 1Gi
              limits:
                cpu: 4000m
                memory: 1.2Gi
    service:
      app:
        ports:
          http:
            port: 8191
