# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: flaresolverr

  values:
    controllers:
      flaresolverr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.6
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
              limits:
                memory: 1Gi
    service:
      app:
        ports:
          http:
            port: 8191
