---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: youtube

resources:
  - ./namespace.yaml
  - ./channel-analytics-mcp
  - ./davinci
  - ./teleprompter
  - ./trends-mcp
  - ./youtube-public-mcp
