---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-mcp-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: navidrome-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: NAVIDROME_USERNAME
      remoteRef:
        key: Navidrome MCP
        property: username
    - secretKey: NAVIDROME_PASSWORD
      remoteRef:
        key: Navidrome MCP
        property: password
