---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-keycloak
  namespace: flux-system
spec:
  path: kubernetes/home-cluster/apps/auth/keycloak/app
  sourceRef:
    kind: GitRepository
    name: home-ops-git-repo

  targetNamespace: auth
  dependsOn:
    - name: cluster-apps-democratic-csi-iscsi

  wait: true
  prune: true
  interval: 5m
  timeout: 30m

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
