# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flate

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**
      - components/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Flate Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup flate
        uses: home-operations/flate/action@dfa3992ed14feb4b04df25fe3397606345f87374 # v0.4.7
        with:
          cache: true
          base: ""

      - name: Run flate test
        run: flate test all --path ./apps

  diff:
    name: Flate Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: pull
          persist-credentials: false

      - name: Checkout Default Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default
          persist-credentials: false

      - name: Setup flate
        uses: home-operations/flate/action@dfa3992ed14feb4b04df25fe3397606345f87374 # v0.4.7
        with:
          cache: true
          base: ""

      - name: Run flate diff
        id: diff
        continue-on-error: true
        run: |
          flate diff all \
            --path ./pull/apps \
            --path-orig ./default/apps \
            -o diff \
            > diff.patch

      - name: Generate Diff
        id: generate-diff
        run: |
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "${GITHUB_OUTPUT}"
          {
              echo "## Flux diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "${GITHUB_STEP_SUMMARY}"

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.generate-diff.outputs.diff != '' }}
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Add Comment
        if: ${{ steps.generate-diff.outputs.diff != '' }}
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: ${{ github.event.pull_request.number }}/flux-diff
          message: |
            ```diff
            ${{ steps.generate-diff.outputs.diff }}
            ```
