# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flux Local

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/**
      - components/**
      - .github/flux-local/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Flux Local Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v8.3.0
        with:
          args: >-
            test
            --all-namespaces
            --path /github/workspace/.github/flux-local
            --skip-secrets
            --kustomize-build-flags=--load-restrictor=LoadRestrictionsNone
            -v

  diff:
    name: Flux Local Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        resources:
          - helmrelease
          - kustomization
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: pull
          persist-credentials: false

      - name: Checkout Default Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default
          persist-credentials: false

      - name: Initialize diff output
        run: touch diff.patch

      - name: Run flux-local diff
        continue-on-error: true
        uses: docker://ghcr.io/allenporter/flux-local:v8.3.0
        with:
          args: >-
            diff ${{ matrix.resources }}
            --unified 6
            --path /github/workspace/pull/.github/flux-local
            --path-orig /github/workspace/default/.github/flux-local
            --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart"
            --limit-bytes 10000
            --all-namespaces
            --skip-secrets
            --kustomize-build-flags=--load-restrictor=LoadRestrictionsNone
            --output-file diff.patch

      - name: Generate Diff
        id: diff
        run: |
          {
              echo 'diff<<EOF'
              cat diff.patch
              echo EOF
          } >> "${GITHUB_OUTPUT}";
          {
              echo "## Flux ${{ matrix.resources }} diff"
              echo '```diff'
              cat diff.patch
              echo '```'
          } >> "${GITHUB_STEP_SUMMARY}"

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.diff.outputs.diff != '' }}
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: ${{ github.event.pull_request.number }}/apps/${{ matrix.resources }}
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
