---
name: Flux Diff
permissions: {contents: read}

on:
  pull_request:
    branches: [main]
    paths: ["apps/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.8.3

      - name: Run flux-local diff
        uses: allenporter/flux-local/action/diff@8.1.0
        id: diff
        with:
          live-branch: main
          path: apps/
          resource: kustomization
          token: "${{ steps.app-token.outputs.token }}"

      - name: Post PR Comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          message-id: flux-diff
          message: |
            ## Flux Diff

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
