---
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push: {}

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup mise
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Run linters
        run: mise exec -- task lint:check
