---
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push: {}

jobs:
  check:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2

      - name: Run linters
        run: mise exec -- task lint:check
