---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleprompter
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: teleprompter

  dependsOn: []

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      teleprompter:
        containers:
          main:
            image:
              repository: ghcr.io/mirceanton/teleprompter
              tag: v3.1.2
            env:
              PORT: &port 8080
              OIDC_ISSUER_URL: https://keycloak.nas.svc.h.mirceanton.com/realms/Homelab
              OIDC_CLIENT_ID: teleprompter
              OIDC_REDIRECT_URL: https://teleprompter.home.mirceanton.com/auth/callback
            envFrom:
              - secretRef: { name: teleprompter-secret }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi

            probes:
              liveness: &backendProbe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/live
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *backendProbe
              startup: *backendProbe

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      teleprompter:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames: ["teleprompter.home.mirceanton.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network-system
