---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./externalsecret.yaml
  - ./oci-repository.yaml
  - ./pvc.yaml

  - ./cpu.helm-release.yaml
  - ./gpu.helm-release.yaml
